### ISSUE TITLE
countinous integration

### ISSUE THREAD

**Issue by Mic92** [Teifun2/nextcloud-cookbook-flutter#1]
To get user-feedback it might be helpful to
deploy beta apps:

https://flutter.dev/docs/deployment/cd

**Comment by Mic92** [comment]
If you are interested I can have a look in setting up a github action for it.

**Comment by Teifun2** [comment]
That sounds very promising! I think the app needs to progress futher before this can become a thing though. Until some basic user functionality is added I would wait.

**Comment by Teifun2** [comment]
@Mic92 If you are still interested in helping to set this up i would be very thankful!

**Comment by Mic92** [comment]
This one solves the CI part: https://github.com/Teifun2/nextcloud-cookbook-flutter/pull/8
Continuous integration needs a bit more work.

**Comment by Philipp5796** [comment]
Would be nice if this will also build for iOS. The irregular, manual distributed, beta apps are currently android only

**Comment by Mic92** [comment]
It should be possible without having a testflight account without an iOS license.

**Comment by Teifun2** [comment]
I cannot build the iOS version myself as flutter can only perform a build on a mac ......
So this woul need to be done by somone else, or i need to check if i can setup a vm, but thats a big hassle and has no priority :( sorry!

I also doubt that it will be easy (possible?) to do automatic build with travis if mac system is required!

**Comment by Mic92** [comment]
Github supports macOS in CI. I personally use https://github.com/kholia/OSX-KVM every once in a while.
However you probably want to have some iOS devices to test it anyway. Maybe some else can step in to that.

**Comment by Teifun2** [comment]
@Mic92 Oh wow :O didnt know that. My GF has a iOS device so i could test the app but she has no mac so thats why i cannot build it. But if we get Travis running i could also test the app that way (a little)

But obviously it would be better to have someone who is really focused on the iOS build

**Comment by Mic92** [comment]
I installed xcode in OSX-KVM but I could not manage to connect ios devices to it - also I did not try very hard. If you don't have to test too much, you could try to upload it to Testflight directly.

**Comment by greendoor8** [comment]
If the primary goal is to test the iOS version on a Mac, I could support you. I have a Mac and could set up the Flutter environment. I'm very interested in an iOS APP for Cookbook in Nextcloud.

**Comment by Teifun2** [comment]
@greendoor8 I would highly appreciate that! When i know that i works i need to figure out how to publish it, but this is another problem.

**Comment by j-koreth** [comment]
Neat didn’t see this discussion. I’ll keep it in mind for the future

**Comment by Leptopoda** [comment]
> Ah a pipeline needs to be setup for automatic builds and deployments,

This is something i want to takle for android builds aswell. Im so anoyed by doing it manually honestly :D

I wonder if there is somewhere a premade github action set for releasing flutter apps. (Best woudl be including ios & android release over API)

_Originally posted by @Teifun2 in https://github.com/Teifun2/nextcloud-cookbook-flutter/issues/178#issuecomment-1495506947_

Continuing the discussion here I'm currently rewriting the CI stuff and could also add apk signing if you like. But I have no experience with google play and therefore CD.

Should I at least add the signing part? You would need to change some ci configs but it shouldn't be that hard

**Comment by Teifun2** [comment]
If you are already on it you can add it. Last time i looked into it i can then store the key in the key safe of github so it will not be exposed but can be sigend with the correct key. i can change these things.

I just found an actiont that could help me 
https://github.com/r0adkll/upload-google-play

i can also try to integrate this if you dont want to.

https://www.valueof.io/blog/deploying-to-google-play-using-github-actions

**Comment by Leptopoda** [comment]
@Teifun2
What apk type are you currently uploading to google play?
A universal APK? APKs split per abi? Or an aab?

Also regardless of that what would you like to use going forward?

**Comment by Teifun2** [comment]
AAB for Google play and one unviersal apk that is then packed into the release for direct download if anyone wants to.

I think this is a good way and i would stick to it :)

**Comment by Teifun2** [comment]
There is now enough CI/CD setup for automatic releases.
