### ISSUE TITLE
Categories failed to load after Nextcloud upgrade

### ISSUE THREAD

**Issue by brusnak** [Teifun2/nextcloud-cookbook-flutter#104]
Getting several errors most of the time. It does load occasionally, but I can always do a search.  On opening the app though I get the image attached.
![Screenshot_20220110-052124](https://user-images.githubusercontent.com/3260421/148758680-a8bd18a4-148f-4e56-81b0-cc0b000d534e.png)

**Comment by Teifun2** [comment]
@brusnak  I will try to have a look why this is happening.

Can you give me the version of your nextcloud instance + cookbook plugin version so i can try to reproduce it?

**Comment by brusnak** [comment]
Currently at Nextcloud 22.2.3, however this has happened across my last 4-5
upgrades.  I honestly don't remember the first version of Nextcloud I
installed.

Cookbook plugin is at 0.9.8

**Comment by Teifun2** [comment]
@brusnak 
I checked with the same cloud and plugin combination and everything works well for me.

Therefore i assume it is a problem with a recipe or a recipe category that breaks the load.

If you are logged into your cloud account in the browser can you try to open the following url:

YOUR-HOST/index.php/apps/cookbook/categories

This should show you a json list of all categories in your cookbook. If this is not working i might need a copy of your cookbook or access to a test account on your server to further investigate this :/

**Comment by brusnak** [comment]
Thanks for your reply.  I am getting a json list.  Would the amount of
entries cause an error like this?  I've got about 370-380 entries.

**Comment by Teifun2** [comment]
@brusnak 
Well this is weird. This should be the data that is also loaded by the app.

I dont think that this amount of data should result in any problems.

There are a few things that we could still try:
1. Logout and login to reset authentication
2. Reinstall the app
3. Send me a zip of your Recipe folder (so i can load it into my instance and double check if there is an issue). Be careful if you have any recipe / image that you don't want to share!
4. The part of the code that throws this exception was reworked recently and is not yet released. Maybe the problem just goes away 😞 ?
5. I get a test account on your instance and can debug directly against your server. (Could be weird issues with web server or web proxy)

**Comment by brusnak** [comment]
Thanks again for all your help.  I went through my entries and deleted
about 10-15 of them that had some weird issues not allowing them to be
edited.  Had to delete through cli.  Anyway, I think this has fixed my
issue.  So far it's worked today.  I'll also update the review in google
play.

**Comment by Teifun2** [comment]
Im happy that it worked out for you! Sadly it is very hard to handle the data as so different recipe sites use different and sometimes "wrong" schemas to store the data. This can sometimes lead to this issue.
