### ISSUE TITLE
Editing recipes in cookbook app throws exception

### ISSUE THREAD

**Issue by patterchon** [Teifun2/nextcloud-cookbook-flutter#111]
Reproducible as follows:
1. Edit a recipe,
2. Change some words in "Zutaten" list or "Zubereitung" list
3. Click "Bearbeiten"
4. Exception occurs

The following error (with red background) is shown:
Aktualisierung fehlgeschlagen Exception type
'_GrowableList<dynamic>' is not a subtype of type
'Map<dynamic, dynamic>' in type cast

System informations:
Fairphone 4 with /e/OS
Nextcloud cookbook app version: 0.75
Nextcloud version: 22.2.3
Cookbook app version: 0.9.9 

I'm not sure, but I think to remember that with nextcloud cookbook app version 0.70 it was working.

**Comment by Kage1** [comment]
I'm having the same issue. I edited an existing recipe description and got it.

**Comment by TomW80** [comment]
I have also the same issue. Is there already a solution?

**Comment by Teifun2** [comment]
Please refer to #110
