### ISSUE TITLE
The button source don't open the link

### ISSUE THREAD

**Issue by michelebossa** [Teifun2/nextcloud-cookbook-flutter#112]
Hi,
I have tried on two differenr android phone but the push button "Source" don't open the link attached on recipies in any browser I suppose it is own scope.

It is a bug or maybe some permission to do? Can you check?

Thanks

**Comment by Teifun2** [comment]
Hello I'm sorry to hear that the button is not working.

It is on my side so it has to be some device / os / recipe (?) specific issue.

Can you send me one recipe where it is not working. Also Device name and OS version number. Maybe i can figure something out!

**Comment by michelebossa** [comment]
Hello,
As requested i share the info:

Recipe https://blog.giallozafferano.it/dulcisinforno/pizza-bonci/
Os Android 12 Version One Ui 4.1
Device Galaxy A52 5G
Thanks.

**Comment by k4ds3** [comment]
I can confirm this issue!

I'm running Android 12 with OxygenOS (Device: Oneplus 8T). I have attached an example recipe that's not working (had to change the file type to .json.txt since GitHub doesn't allow .json files to be directly attached).

My default browser in Android is Firefox, but I also have Chrome (pre-)installed


I have used adb logcat to see the device logs when pressing the Source button, this is what I got:
```
04-12 13:26:01.715 17255 17255 V AutofillManager: requestHideFillUi(null): anchor = null
04-12 13:26:01.863 17255 17255 I UrlLauncher: component name for https://www.halfbakedharvest.com/basil-garlic-oil-noodles/ is null
```

I hope this information can help you!

[recipe.json.txt](https://github.com/Teifun2/nextcloud-cookbook-flutter/files/8472259/recipe.json.txt)

**Comment by Teifun2** [comment]
@michelebossa @k4ds3  Thanks for the input.

I checked the recipe (pizza-bonci) so it seems not to be related to the recipe json itself. 

The logs provided by @k4ds3 might help i need to check if i find anything about this issue!

**Comment by Teifun2** [comment]
Aha i found something. According to some stackoverflow issues from API 30 and onwards i need to define some things for this to work!

https://pub.dev/packages/url_launcher#android

**Comment by Teifun2** [comment]
@k4ds3 @michelebossa could one of you test this prerelease: https://github.com/Teifun2/nextcloud-cookbook-flutter/releases/tag/wip-0.7.7

I built it with the required Manifest changes!

**Comment by k4ds3** [comment]
> @k4ds3 @michelebossa could one of you test this prerelease: https://github.com/Teifun2/nextcloud-cookbook-flutter/releases/tag/wip-0.7.7
> 
> I built it with the required Manifest changes!

Can confirm that your fix works! ❤️

**Comment by Teifun2** [comment]
Perfect :) Thanks for the confirmation!

**Comment by michelebossa** [comment]
Hi,
I can't test becouse i'm using a Company phone without possibility to download an apk outside google play.

Sorry
