### ISSUE TITLE
Use Nextcloud app account to log in

### ISSUE THREAD

**Issue by jimbolaya** [Teifun2/nextcloud-cookbook-flutter#117]
Currently, it's required to use an App password to connect to my server. I'd like to be able to use the Nextcloud account already on the phone. 

Is this planned at some point?

**Comment by Teifun2** [comment]
Currently this is not planned. As this feature is highly OS specific and i still have the goal to release this app on IOS aswell where this would not work.

Maybe if somone is dedicated to implement it i would add support for it but its not on my priority list. Sorry!
