### ISSUE TITLE
NoSuchMethodError: addAll

### ISSUE THREAD

**Issue by nicofrand** [Teifun2/nextcloud-cookbook-flutter#118]
Hi! Thanks for the app! I met a bug when creating a recipe:

**Description**
I cannot create a recipe manually. I installed the latest version from Fdroid.

**Reproduction**
1. Click the + button to create the recipe
2. Fill the inputs (at least title, duration, ingredients, steps)

**Expected behavior**
The recipe is created.

**Actual behavior**
An error is thrown and displayed.

**Screenshots**
![Screenshot_2022-03-27-14-19-09-868_com nextcloud_cookbook_flutter](https://user-images.githubusercontent.com/3419050/160281288-20db5709-7e0a-49a3-901c-43a86fb2b010.jpg)

**Comment by lom-off** [comment]
+1
The same error :(

**Comment by Teifun2** [comment]
I found the issue and creating a fix. Sorry for the long awaited response :/
