### ISSUE TITLE
Please provide description, screenshots and license

### ISSUE THREAD

**Issue by IzzySoft** [Teifun2/nextcloud-cookbook-flutter#12]
As a follow-up [from here](https://github.com/nextcloud/cookbook/issues/207#issuecomment-674685074), answering your question on what's next: Some description, screenshots etc would be great to have (people tend to skip apps with no details). Best way to do that would be adding [Fastlane structures](https://gitlab.com/snippets/1895688) to your repo here. Also please add a license (GPL-3.0, MIT or whatever you decide on). Updating the Readme (which is still the default one from the Flutter boiler-plate) wouldn't hurt either :wink:

PS: Your app will show up [here](https://apt.izzysoft.de/fdroid/index/apk/com.nextcloud_cookbook_flutter) with the next sync tomorrow evening. Description etc. will be updated as soon as you provide it and let me know.

PPS: According to VT, MS thinks your app [holds a Trojan](https://www.virustotal.com/gui/file/77e168e815eda13021b94a47c9863afc459311a7a03e755560c45645a90725c2/detection). Guess we can ignore that, but just letting you know.

**Comment by Teifun2** [comment]
Yiiikes what's that trojan :/ i need to check that out ASAP! Thanks for the sync and I will add the information you requested over time!

**Comment by IzzySoft** [comment]
Yes, I also assume a false positive – for at least two reasons: it's only 1 out of 62 engines reporting it, and it's Windows specific (and thus makes no sense in an Android app). Sad thing is they don't provide much details, so it's hard to figure what triggered it. I'd ignore it for now and focus on the other things. At times, a rescan some weeks later makes it disappear, or the next version of the app is not found having it.

Looking forward to description & screenshots so I can improve the listing, which currently looks a bit bare-bones :smiley:

**Comment by Teifun2** [comment]
finally i hate some minutes time, 

License and image are there, description is very bare bone ^^

**Comment by IzzySoft** [comment]
Thanks! I've just added the screenshots and updated the license, changes will go live with the next sync tomorrow. If you want to link to [your app in my repo](https://apt.izzysoft.de/fdroid/index/apk/com.nextcloud_cookbook_flutter), you can use [this badge](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :wink:

Just let me know if you update(d) the description, or need something else changed.

**Comment by Teifun2** [comment]
Ive added the badge now! i will close this issue now but i might ping you again if i need any information :=) thanks for your help!

**Comment by IzzySoft** [comment]
Great! And yes, ping me when needed.
