### ISSUE TITLE
Missing translation of "Hours" and "Minutes"

### ISSUE THREAD

**Issue by cloud2018** [Teifun2/nextcloud-cookbook-flutter#123]
Version 0.7.6

"Hours" and "Minutes" are not translatable va Transifex
(trifle: After "Hours" is ":" after "Minutes" not)

![nc_cookbook_flutter_1](https://user-images.githubusercontent.com/34692335/163677339-80f029a7-7d5a-46dc-b6f1-f1ba62eaba63.jpg)

**Comment by Teifun2** [comment]
Thanks @cloud2018  for this one. You are absolutely right this was missed in the creation of the DurationFormField :)
