### ISSUE TITLE
language setting is not used after restart

### ISSUE THREAD

**Issue by cloud2018** [Teifun2/nextcloud-cookbook-flutter#124]
Version 0.7.6

It looks like the selected language is only used if the settings for the language has been opened before otherwise the standard language is used

**Steps to reproduce:**
1. In settings select a language that is not the default language of the smartphone
2. As expected, all will be displayed in the selected language
3. Stop the app
4. Start the app
5. See Error:
 i) Instead of the selected language,  all will be displayed in the default language
 ii) Go to settings: The selected language is displayed (saved) , but it is not used after the restart

**Comment by Teifun2** [comment]
@cloud2018  This is a very strange behaviour! I will check it out and see if i can reproduce this! Thanks for the report!

**Comment by Teifun2** [comment]
i dont know how i ever missed this but for sure. The Setting was never loaded on startup! Thanks for the report!
