### ISSUE TITLE
Translation Unfavorable

### ISSUE THREAD

**Issue by TomW80** [Teifun2/nextcloud-cookbook-flutter#125]
When I want to change a recipe, I have to click on the pencil in the upper right corner to edit. After the change I have to click on the "Bearbeiten" button to save the changes. This is confusing because I am already in edit mode. For me, the button should say "Änderung speichern".

![Screenshot_20220417_111633_com nextcloud_cookbook_flutter](https://user-images.githubusercontent.com/54640793/163708333-9fc1fb7b-3edb-4dca-9dac-6f03750e1358.jpg)

**Comment by Teifun2** [comment]
Hello @TomW80 

With the changes of #121 this should be reflected in the translations as soon as the german translations are updated in transifex!

I hope this suits your request otherwhise please open the issue again and elaborate!
