### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [Teifun2/nextcloud-cookbook-flutter#134]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 10 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on Nextcloud Cookbook Mobile Client (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve Nextcloud Cookbook Mobile Client's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by Teifun2** [comment]
Please shar everything you know with me 
nextlcoud.cookbook.flutter@gmail.com

However i doubt that these are things that i can change, and i assume these are things related to dart / flutter
