### ISSUE TITLE
Can't add an image for the recipe

### ISSUE THREAD

**Issue by blogdemoi** [Teifun2/nextcloud-cookbook-flutter#135]
Hi,

There is no way to add an image for the recipe. Instead, a Nextcloud adress is shown in the image field and there is no way to add another one, please see screenshot below.

![Screenshot_20220508-152223](https://user-images.githubusercontent.com/83965802/167298563-b3700c2b-3584-46be-b87b-bccc7f273c4b.png)

Thank you.

**Comment by Teifun2** [comment]
Duplicate of  #102
