### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [Teifun2/nextcloud-cookbook-flutter#14]
is there a way (or will there be a way) to translate your nextcloud cookbook app into other languages?

**Comment by Teifun2** [comment]
This is definitively something i will start working on soon. currently i'm still working on basic functionality.
Are you interested in helping with translations?

**Comment by mondlicht-und-sterne** [comment]
yes of course.
on github translate with pullrequest I don't understand something like that.
but I like to translate.

**Comment by kojid0** [comment]
I'd be happy to translate your app into German. I can do PR when you tell me which files to translate. 

@mondlicht-und-sterne What language do you want to translate into? Probably German as well, according to you name? So if you want to, you can translate, send me the files, I'll recheck/confirm and make a PR. Up to you. :)

**Comment by mondlicht-und-sterne** [comment]
@kojid0 ah thanks so i must only search where are the strings to translate and than i open an new issue ?

**Comment by kojid0** [comment]
@mondlicht-und-sterne No, wait for the dev, he might set up some kind of translation platform like https://github.com/Arbify/Arbify and will tell how to do it.

**Comment by mondlicht-und-sterne** [comment]
@kojid0 Yes, of course I am waiting. That was just a question of how I should proceed.

Also i have my first (german) exhibition opening on friday in berlin / germany, where i promote opensource projects. There I am still in the last preparations.

Oh, I did not know the ARB files localization tool yet. Is it opensource?

**Comment by mondlicht-und-sterne** [comment]
@kojid0 

@Teifun2 

it's been 4 weeks now, are there any news about translating?

**Comment by Teifun2** [comment]
@mondlicht-und-sterne
Sadly I was not yet able to add the translation feature due to time restrictions (I do this as a hobby project)

I will notify you on this issue when the feature arrives!

**Comment by Teifun2** [comment]
Just to keep you updated. Im currently trying to figure out if there is a way to include all translations that have already been done for the nextcloud plugin in this project. This would save us a huge workload on translations, and only some few phone app specific messages would still be missing.

**Comment by mondlicht-und-sterne** [comment]
you can take this one https://weblate.bubu1.eu/

because at hosted weblate you must pay.

and everybody can translate

**Comment by Teifun2** [comment]
So to update this. 
I now created the possibility to translate the App and added initial English and some German translation.

I will now try to integrate it with Transifex, ideally under the Nextcloud Project.

**Comment by mondlicht-und-sterne** [comment]
With transifex I have to pass, I no longer have that.

**Comment by Teifun2** [comment]
I was informed that translation over transifex is very fast, and the whole nextcloud project is there. So i hope we will soon have translations for everything that is needed.

**Comment by Teifun2** [comment]
So i added translation to the new verison. (Currently only german and i think some strings are not yet properly translated)

As soon as the integration with transifex is running i hope more languages will come. 
But with that i will close this issue.
