### ISSUE TITLE
Category "All" is assignable to a recipe

### ISSUE THREAD

**Issue by cloud2018** [Teifun2/nextcloud-cookbook-flutter#141]
The category "All" is selectable when you open the selection box while editing a recipe. 

The category "All" should not be a "normal/standalone" category, "All" should be the superset of all categories. Therefore, "All" should not be explicitly assignable to any recipe and not selectable when editing a recipe. 

Version: nextcloud-cookbook-flutter 0.7.6

**Comment by Teifun2** [comment]
Thanks this is a good point. I forgot to remove this. It will be fixed with the next version!
