### ISSUE TITLE
Upgrade to flutter 3.0.5

### ISSUE THREAD

**Issue by TDuffinNTU** [Teifun2/nextcloud-cookbook-flutter#144]
To improve the maintainability and reduce technical debt of the app, it might be worth moving to Flutter 3.0.5, as well as upgrading packages that have improved null safety implemented in this version. There's also the opportunity of moving to Material 3/Material You when these new themes are stable!

I can successfully launch debug builds locally with 3.0.5 on android, so I'd be happy to help with this! 

I'd also recommend setting the android target SDK to 33. Some packages require this to offer their full featureset on Android.

**Comment by Teifun2** [comment]
Thanks for the info. I will try to update with the next release!
