### ISSUE TITLE
Doesn't work with plugin 0.9.15 (NC 24.0.4)

### ISSUE THREAD

**Issue by th-2021** [Teifun2/nextcloud-cookbook-flutter#148]
I just upgraded my nextcloud to 24.0.4 and now the app doesn't work any longer. Cookbook plugin is 0.9.15rc.

**Comment by psleep** [comment]
Same here - v0.9.15 and NC v 24.0.4.
Even tried resetting my login details but the app just doesn't authenticate anymore - gives me username/password is incorrect error.

@Teifun2 if you need/want any specific logs then let me know

**Comment by saschamander** [comment]
I'm currently running Nextcloud 23.0.7 and the Cookbook App on Version 0.9.15.

I can still log in and view the recipes in the list view, but when I want to view a specific one i get following screen:
![Screenshot_20220909-153437](https://user-images.githubusercontent.com/8129465/189362740-b6e71b65-af9e-410c-84ca-82747a8fad0f.jpg)

**Comment by skyrid3r698** [comment]
For anyone else searching for a Workaround until this is fixed. You can downgrade this app by downloading the last release from the nextcloud store, deactivate cookbook in your admin interface, delete the current "cookbook" folder under /apps and extract your downloaded zip in there to replace the deleted "cookbook" folder. Now activate your cookbook app again.

**Comment by Teifun2** [comment]
Thanks for the report on this issue. I will check it and hope that i can find a fix!

**Comment by prometheus42** [comment]
I had the same issue and investigated the problem. Seems like the cookbook app deprecated the old API endpoints. Instead of `/api/category/{category}` the endpoint can now be found under `/api/v1/category/{category}`. The old endpoints were removed in the [pull request 1200](https://github.com/nextcloud/cookbook/pull/1200/commits/28f0cfc3fba9dce4767207ef742f0c376116dd28) some days ago.

**Comment by christianlupus** [comment]
I just stumbled over this issue. It is interesting, that things are not working as expected.

I replaced the old endpoints, yes that one is true. But the version 0.9.15 had them still enabled in deprecated fashion. So, it should be working in general. 

The main difference is that the login has been modified. Until the change, the app allowed both session based authentication as well as API based authentication. These two have been separated for security reasons. 

As far as I understand dart (not very well), for example [on this line](https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/d45f51c307f870c0877bca7bf282b8d6e1cadea1/lib/src/services/categories_provider.dart#L18), the request is send using a session based (cookie based) authentication. Only, the url is used but not the basicAuth header.

**Comment by Teifun2** [comment]
@christianlupus I was also not able to reproduce the issue with 0.9.15 soi i am not 100% sure if this will fix it but i will try.

The Line you posted is actually using a custom Network implementation (to cache images)

and it adds the basicAuth Header [here](https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/develop/lib/src/services/network.dart#L25)

**Comment by christianlupus** [comment]
I am sorry, it was just a quick glance and i am **not** fluent with dart. 

With the additional authentication header it should work in general. As I see another issue that might be caused by similar means, please provide a minimal feedback on the results, you find. I will do the same.

**Comment by Jolopu** [comment]
> I'm currently running Nextcloud 23.0.7 and the Cookbook App on Version 0.9.15.
> 
> I can still log in and view the recipes in the list view, but when I want to view a specific one i get following screen: <img alt="" width="150" src="https://user-images.githubusercontent.com/8129465/189362740-b6e71b65-af9e-410c-84ca-82747a8fad0f.jpg">

Exact same issue here on NC 22.2.10 and plugin 0.9.15. I downgraded to 0.9.14 and it works again.

**Comment by Teifun2** [comment]
@Jolopu This is very weird. I have the same NC Version and the same Plugin version and it works for me.

Just to make sure you tried it with the newest App version? 0.7.7 (only availble here on github currently it is not yet published to the app store)

**Comment by psleep** [comment]
@Teifun2 I just installed 0.7.7 on Android.
Updated Nextcloud Cookbook app to 0.9.15.
NC version is 24.0.5
I use 2FA so I have an App Password configured for nextcloud but I get an authentication error 500 and subsequent attempts result in username/password is incorrect

**Comment by psleep** [comment]
@Teifun2 I have emailed you

**Comment by psleep** [comment]
@Teifun2 weirdly after re-creating my app password for cookbook (the original had vanished from my nextcloud settings) I can now login to the Cookbook android app 0.7.7 but the images are just plain knives and forks rather than the previews I used to get

**Comment by Jolopu** [comment]
> @Jolopu This is very weird. I have the same NC Version and the same Plugin version and it works for me.
> 
> Just to make sure you tried it with the newest App version? 0.7.7 (only availble here on github currently it is not yet published to the app store)

Ok. I'm still on 0.7.6. Will update once it's available on F-Droid.

**Comment by Jolopu** [comment]
Updated to 0.7.7 from f-droid and now I'm stuck on login. (NC 22.2.10 and plugin 0.9.15)

**Comment by Teifun2** [comment]
@psleep Thanks for the test account. I was able to reproduce the bug with this, and could understand it better.

@christianlupus Very weirdly the only endpoint fully affected on the server is:
/apps/cookbook/api/v1/recipes/:id
All others work without the new api urls. I was not able to find out why :)

I hope that for everyone the problems are solved with 0.7.8

If not please open a new issue so we can start a new topic.

**Comment by psleep** [comment]
@Teifun2 no worries - I've deleted the account now.
Thanks for all your hard work and the fast response!

**Comment by christianlupus** [comment]
> @christianlupus Very weirdly the only endpoint fully affected on the server is:
> /apps/cookbook/api/v1/recipes/:id

So, you mean that the fetching of a single recipe (I suspect you were referring to the GET verb) was working as expected or caused trouble?

I will have to check your code to see the exact differences. The fix is between 0.77 and 0.7.8?

> All others work without the new api urls. I was not able to find out why :)

What do you mean by "without the new api urls"? Are you still using the deprecated urls as before the 0.9.15 version? These will be removed on 0.9.16. I just want to make sure you are not surprised by the next release again.

**Comment by Teifun2** [comment]
@christianlupus 
Sorry my comment was not very precise.
So the app didnt use the /api/v1 URL Schema before. (it is now thanks to [prometheus42](https://github.com/prometheus42))
See: https://github.com/Teifun2/nextcloud-cookbook-flutter/pull/154

Weirdly All Endpoints where still wroking with 0.9.15 EXCEPT the 
GET /apps/cookbook/recipes/:id

I hope this explains the issue better. Why only this GET endpoint and why it didnt affect all server (for mine it was not a problem) i have no clue!

**Comment by christianlupus** [comment]
Oh, sorry. This was my bad. I missed this line in duplicating the routes: https://github.com/nextcloud/cookbook/blob/32b40bfdb8194a2b46d9d1d0c83431bc47e08983/appinfo/routes.php#L83

This means that the crud operations on recipes will fall without /api/v1.
