### ISSUE TITLE
Preparation time enhancements 

### ISSUE THREAD

**Issue by kojid0** [Teifun2/nextcloud-cookbook-flutter#15]
Please add the correct unit to the time, e.g. min/minutes or h/hours.
Also, please consider a consistent scheme like "(h)h hours (m)m minutes" (so "2 hours 5 minutes" instead of 2:5).
In this [example](https://www.chefkoch.de/rezepte/2609101409859076/Haehnchen-Wrap-mit-Honig-Senfsauce.html), preparation time + cooking time != total time, because "resting time" is missing. Resting time is not implemented in nextcloud cookbook yet, I made an issue [there](https://github.com/nextcloud/cookbook/issues/312), hope you can add this as soon as it got implemented on the other side :) 

![photo_2020-08-26_16-40-13](https://user-images.githubusercontent.com/24477557/91317858-d6afcc00-e7ba-11ea-88e9-406360f04797.jpg)

**Comment by Teifun2** [comment]
Thanks for reporting this bug! Indeed the 2:5 should be displayed as a 2:05. 

As i will follow the implementation on nextcloud i cannot add the resting time. I will also not add unit signifiers "2h 5m" or something similar, as i want to keept it as similar as the nextlcoud plugin on the web. 
If the web changes the times to an other format i will also start doing that!
