### ISSUE TITLE
doed not work with nextcloud 24.0.5, changed API

### ISSUE THREAD

**Issue by xundeenergie** [Teifun2/nextcloud-cookbook-flutter#151]
Can not show recipes in case of wrong api.

The app searches on
https://\<nextcloudurl\>/index.php/apps/cookbook/api/recipes/\<id\>

But now recipes are now on
https://\<nextclouddomain\>/apps/cookbook/#/recipe/\<id\>

**Comment by Teifun2** [comment]
Possibly related to this #148

I hope the solution of @prometheus42 works for your issues aswell!

**Comment by fz72** [comment]
I have testet it with release 0.7.7 from github. Unfortunately it doesn't work for me. I'm using Nextcloud 24.0.5 and cookbook 0.9.15. It seems the app still uses the old url scheme.

**Comment by fz72** [comment]
After wiping data and uninstalling the f-droid version it works for me with github version 0.7.7. Thanks for your quick help Teifun2.

**Comment by Teifun2** [comment]
I hope that with the version 0.7.8 the problems are resolved!
