### ISSUE TITLE
Category: Show all

### ISSUE THREAD

**Issue by kojid0** [Teifun2/nextcloud-cookbook-flutter#16]
Please add a category "All recipes" where all recipes are shown. I thought "*" will show all recipes but it doesn't. It's working correctly in nextcloud cookbook app.

**Comment by Teifun2** [comment]
Yes indeed the "*" category contains all recipes that are not assigned to a category!
i will add an "all" category as soon as i get to it. Thanks for your feedback!

**Comment by Teifun2** [comment]
I added this in release 0.3.3
3ac08ed3b2c28a174f93eb9a1bdea8fccd468199
