### ISSUE TITLE
Still can't login

### ISSUE THREAD

**Issue by rodude123** [Teifun2/nextcloud-cookbook-flutter#160]
So I removed 2fa to see if I could login and I can. When I logged in and re-enabled 2fa I got an error 401 unauthorized even though I selected `use app password` before. I'm using version 0.7.8. Can someone else try this and confirm please

**Comment by k4ds3** [comment]
I'm using app version 0.7.8 with Nextcloud version 24.0.5 and it works using 2fa and an app password generated in my profile security settings. Maybe your Nextcloud version is outdated or something?
