### ISSUE TITLE
Infinite loading page on startup

### ISSUE THREAD

**Issue by bricebou** [Teifun2/nextcloud-cookbook-flutter#166]
Using Cookbook 0.9.15 on a self hosted Nextcloud 24.0.6, I'd like to use you app on its latest version 0.7.8 on Android.

When launching the Android app, I only get a loading page with the loading gif under a dark overlay...

 Any idea ?

Thanks in advance !

**Comment by Teifun2** [comment]
Hello @bricebou 

I assume this happens even before the login?

If so then this sounds very strange. I must assume that some library that is initializing in the beginning is crashing.

Sadly i cannot figure out what exactly is happening as i never had this issue. I would need debug logs from the phone that this is happening in the hopes that they indicate anything that could cause this.

**Comment by bricebou** [comment]
Hi,

Yeah, it happens before the login screen.
But, when installing via FDroid, the app works perfectly!
I'm not familiar enough with Android to get the first clue on what's going on...

**Comment by Teifun2** [comment]
Hmm that is peculiar.

To my knowledge the F-Droid Version and the Playstore Version should be the exact same code, so i have no idea why this happens.

Is it ok for you if i close the issue as you found a workaround?

**Comment by bricebou** [comment]
I don't understand what the problem is, I tried several times to remove completely the app installed through the PlayStore, and the result was the same, each time...
Yes, I'm closing this issue.
Thanks a lot for this great app :-)
