### ISSUE TITLE
APK to try would be fine? Perhaps F-Droid?

### ISSUE THREAD

**Issue by poltrian** [Teifun2/nextcloud-cookbook-flutter#17]
APK to try would be fine? Perhaps F-Droid?

**Comment by poltrian** [comment]
found it on Izzy. What a nice pice of Software, thank you so much

**Comment by Teifun2** [comment]
Thanks for your feedback. I will add a Badge to the Izzy repo on the main page of this git repo!
If you find any bugs or see how to improve please let me know!
