### ISSUE TITLE
iOS app not visible on default branch

### ISSUE THREAD

**Issue by maurerle** [Teifun2/nextcloud-cookbook-flutter#170]
Hi,

the link to the iOS app is currently not visible on the default branch (develop) but only on master.
So this should either change the default branch to master or backport the merged PR to develop to provide greater visibility to the iOS release :)

I was looking for it for quite some time.
Thank you for the work!

**Comment by Teifun2** [comment]
ups that is a mistake on my side sorry.

**Comment by Teifun2** [comment]
I Just fought with the styling of the button, but it is now done! Thanks for the heads up!
