### ISSUE TITLE
Api deprecated

### ISSUE THREAD

**Issue by wintstar** [Teifun2/nextcloud-cookbook-flutter#178]
Samsung Galaxy A 53 5G
Android 13
Android App Version 0.7.8
Nextcloud Version 25.0.5

Recipes are no longer displayed in the app

![Screenshot_20230325_112117_One UI Home](https://user-images.githubusercontent.com/2753863/227716695-841c224f-65d8-441f-90a1-6be02313fdc6.jpg)
![Screenshot_20230325_130248](https://user-images.githubusercontent.com/2753863/227716697-bcd2165b-c618-47de-9c1e-bf74668ef2df.jpg)

Recipes are no longer displayed in the app

**Comment by Leptopoda** [comment]
this has been fixed by #177 

still waiting for a new release though :)

**Comment by Teifun2** [comment]
I pushed a new version to google play aswell. It will take a bit untill it is reviewed.

**Comment by wintstar** [comment]
The new Version work. Many thanks for Update.

**Comment by goebbe** [comment]
The update seems to be already available on the Playstore - but not yet on Fdroid.
Has the new release/PR been sent to Fdroid?

**Comment by Leptopoda** [comment]
@goebbe 
Fdroid has picked up the changes but hasn't made a build yet. As always this can take a few days.

![IMG_20230327_105901.jpg](https://user-images.githubusercontent.com/25266387/227894161-2dfe61c6-b0c3-411a-9afe-7ce9d8880726.jpg)

https://gitlab.com/fdroid/fdroiddata/-/commit/0ff3f2fea55a2dc51d10cb9d4bd3ab4a348ad02a

**Comment by SurfinBirdman** [comment]
Any news on when this will be updated in iOS?

**Comment by a3linux** [comment]
Same question here as above. iOS app is broken.

**Comment by Leptopoda** [comment]
I don't know how long f-droid usually takes but it seems odd that the changes have been picked up for so long but not approved yet.

maybe you can instigate this @Teifun2

**Comment by djcath** [comment]
@j-koreth  i know you worked hard on the initial iOS release.   Was there a way for you to streamline these updates? i love my ios app and i was stupid enough to update the cookbook version and now my app is broken, even after trying to rollback to an older version of the cookbook plugin.

**Comment by j-koreth** [comment]
Ah a pipeline needs to be setup for automatic builds and deployments, right now I am subscribed to the release tags on the main repo. 

I actually updated the TestFlight beta pretty quickly, waiting on review from apple right now.

**Comment by djcath** [comment]
> Ah a pipeline needs to be setup for automatic builds and deployments, right now I am subscribed to the release tags on the main repo.
> 
> I actually updated the TestFlight beta pretty quickly, waiting on review from apple right now.

That's awesome,  thanks so much for the quick reply and great to know your on top of it

**Comment by j-koreth** [comment]
Try https://testflight.apple.com/join/leE86yyq

**Comment by djcath** [comment]
> Try https://testflight.apple.com/join/leE86yyq

Legend!  works again!

**Comment by Teifun2** [comment]
> Ah a pipeline needs to be setup for automatic builds and deployments,

This is something i want to takle for android builds aswell. Im so anoyed by doing it manually honestly :D

I wonder if there is somewhere a premade github action set for releasing flutter apps. (Best woudl be including ios & android release over API)

**Comment by getwet** [comment]
> Try https://testflight.apple.com/join/leE86yyq
> 
> 

Works for me too. Very good! 😊👍

**Comment by Teifun2** [comment]
@Leptopoda If i understand correct this should be now fixed, is that correct?

**Comment by Leptopoda** [comment]
I checked a week or so ago an my girlfriends iPhone and it looked like it is still in  beta there.
@j-koreth would need to clarify.

**Comment by Leptopoda** [comment]
Looks like it has been released 3 days ago.
