### ISSUE TITLE
Error Exception type: '_OneByteString' is not a subtype of type 'int'

### ISSUE THREAD

**Issue by rodude123** [Teifun2/nextcloud-cookbook-flutter#196]
I get the error in the title when trying to open a recipe. I checked F-Droid for an update and there wasn't one. So I'm assuming I'm using the latest version.

**Comment by ripper17** [comment]
I get the same error:

[Nextcloud Hub 3](https://nextcloud.com/) (25.0.5)
Cookbook Version 0.10.2
Nextcloud Cookbook App Version 0.7.8

**Comment by Darnokiv** [comment]
I also get the same error message. I can import or create recipes, but open or editing is not possible.  Furthermore, when opening the app, I get a warning about a chnaged API-Version. 

NextCloud with 25.0.2 (I use the TrueCharts App)
Cookbook with 0.10.2
NextCloud Cookbook iOS App with the latest version

I would be glad about any help, please let me know if you need more info or a screenshot

**Comment by Darnokiv** [comment]
#178 

Encounterd the same Error, but seems they already fixed it and just wait for the stores to publish the new version

**Comment by ripper17** [comment]
Oh, indeed - and now there's an update on F-Droid available to 0.7.9 that fixes the issue.

Thanks for the great work and sorry for the noise. I tried to search for the issue but neither google nor ddg nor my search on github revealed anything...

**Comment by Leptopoda** [comment]
closing in favor of the mentioned #178
