### ISSUE TITLE
Cannot Reach server

### ISSUE THREAD

**Issue by khaytsus** [Teifun2/nextcloud-cookbook-flutter#20]
I don't even get to a login, it simply says it cannot reach the server.  Perhaps because I'm using a custom port, no idea.  logcat isn't very useful, but here's what I see:

10-04 10:59:32.787 16836 16869 I flutter : LoginButtonPressed {serverURL: https://domain:10443}
10-04 10:59:32.787 16836 16869 I flutter : Transition { currentState: LoginFailure { error: Cannot reach: https://domain:10443 }, event: LoginButtonPressed {serverURL: https://domain:10443}, nextState: LoginLoading }
10-04 10:59:32.850 16836 16869 I flutter : Transition { currentState: LoginLoading, event: LoginButtonPressed {serverURL: https://domain:10443}, nextState: LoginFailure { error: Cannot reach: https://domain:10443 } }

The primary NextCloud client works fine, from a browser on the device works fine, etc.  I've tried domain.com:10443 and https://domain.com:10443 both formats in case that matters, both are the same result.

**Comment by Teifun2** [comment]
Hmm I have not yet tested how it acts with a port. I will test this as soon as I have time and get back to you!

**Comment by Teifun2** [comment]
My nextcloud server just crashed (hardware issues) and i'm on vacation so it is a little complicated for me to setup an instance with the requirements. Would it be possible for you to create a test account on your instance and send me the details over elements / riot matrix chat? @teifun2:matrix.org This would help me to debug this issue without forcing me to setup a new environement which would be greeaaat :D

**Comment by khaytsus** [comment]
I can do that, but can't do matrix..  It's a awful heap of crap that is so slow, silly, and convoluted I won't fool with it.  I actually tried here, but it refuses to do anything unless I install the desktop app which I am not doing.

Email me at this username on gmail if you can do that please and I'll pass along credentials I just created.

**Comment by Teifun2** [comment]
Seems to be an ssl certificate issue. (more details in PM)
I need to log this information to the user so that it is clearer :/

**Comment by khaytsus** [comment]
This turned out to be an error on my part...  Most modern browsers are fine with either certificate that Let's Encrypt gives you, but Android seems to need to use the "fullchain" key.  I switched to it on my NextCloud instance and no more login problems.  It had nothing to do with the port, etc.
