### ISSUE TITLE
Material 3 design user avatar and ingredient groups

### ISSUE THREAD

**Issue by arroyoj** [Teifun2/nextcloud-cookbook-flutter#201]
@Leptopoda, thanks for the new material 3 design. While testing out the new app, I noticed that the user avatar is no longer a perfect circle but is now an oval:
![user_avatar_oval](https://user-images.githubusercontent.com/82246664/236367614-7fcd78bb-2900-4d34-af45-fc352c631ed1.jpeg)
It looks like there is a missing `Center()` around the `UserImage()`. I'm happy to submit a PR to fix that, but I wasn't sure if you were done working on that part.

Also, I noticed a change in how ingredient groups are displayed in the new design. Now the group names are centered instead of left aligned. Was that intentional? If not, I can submit a PR to restore the previous layout. For reference, here are screenshots from v0.7.9 vs the new design.
v0.7.9:
![ingredient_group_0 7 9](https://user-images.githubusercontent.com/82246664/236367878-d513b671-1eaa-4e6a-8c64-6f438eb5a4dd.jpeg)
current version: 
![ingredient_group_develop](https://user-images.githubusercontent.com/82246664/236367912-cb7e0acc-7e79-4b02-8e83-6e7bc9167eec.jpeg)

**Comment by Leptopoda** [comment]
> I noticed that the user avatar is no longer a perfect circle but is now an oval:

Yeah I also noticed this and forgot to fix it.

> Now the group names are centered instead of left aligned. Was that intentional?

I think aligned to the start should be better.

PRs as always welcome :)

EDIT: I just assigned you for now
