### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#21]
Hi,

Just taking the app for a test drive. Recipes show up fine, but images aren't loading. Anything I can do to troubleshoot this?

Thanks!

**Comment by Teifun2** [comment]
Hi

Thanks for testing and reporting. That is much appreciated!

This is weird as I have never encountered this before! Thumbnails and  full pictures are not loading? Is it a constant loading circle or does it finish at some point?

Android version?

**Comment by GutHib** [comment]
Neither tumbnails nor full images. It finishes at some point and loads a small square icon indicating that the link is somehow "broken". Works fine in the web app, though.

Android version 9 (lineage).

**Comment by Teifun2** [comment]
Hmm very weird behavior. Could you check manually if the link to the images works?

`{YourHost}/index.php/apps/cookbook/recipes/{RECIPE_ID}/image?size=thumb`

Please replace the host and recipe id.
The index.php needs to be there even if you don't use it for your normal site access.
You can find the recipe_id by opening a recipe in the web view and then you find the recipe id in the url.
Example: apps/cookbook/#/recipe/**815558**

**Comment by GutHib** [comment]
Ok, I figured it out. {YourHost} is a subdomain in my case. Since I was having problems with a second login (see ticket #22) I resorted to using www.domain.com/subdomain instead of subdomain.domain.com which breaks the images. Fair enough.

So this is not an actual bug, and I'll just have to wait until #22 is fixed then.

**Comment by Teifun2** [comment]
Ok thanks for the clarification. I will close this issue then.

On the #22 I will give some more information about that topic!
