### ISSUE TITLE
[Feature Request] Keep screen on

### ISSUE THREAD

**Issue by jsmueller7** [Teifun2/nextcloud-cookbook-flutter#216]
When working with this app the screen goes into lock mode after a while. This is very uncomfortable if you've got your fingers covered with something else. A feature that keeps the screen on would be very welcome.

**Comment by Go-rom** [comment]
Hello,

I agree with this feature request.

In the meantime, you may be interested by this android app : https://f-droid.org/en/packages/com.github.muellerma.coffee/

**Comment by jsmueller7** [comment]
Great. Thank's for the hint!

**Comment by shagn** [comment]
@jsmueller7 The app should already have the feature I think (see [Relase note v0.7.0](https://github.com/Teifun2/nextcloud-cookbook-flutter/releases/tag/0.7.0)). In the most recent version 0.7.9 from the Play Store it is the first option under settings.

![cookbook-stay-awake](https://github.com/Teifun2/nextcloud-cookbook-flutter/assets/16029092/1ac1b19e-cc33-437f-ac91-3df4cce96ff8)

**Comment by jsmueller7** [comment]
Indeed. Thank you for pointing this out!

**Comment by jsmueller7** [comment]
I think the issue can be closed ;)
