### ISSUE TITLE
Same URL, different logins?

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#22]
It seems to be impossible to log in with different usernames under the same URL. Once you've entered an URL you have entered before, you are automatically logged in to the previous account.

I found a workaround so the URL I entered seems like a different one, but sooner or later, someone else will probably run into this problem, so I thought I'd mention. ;)

**Comment by Teifun2** [comment]
Yes, I have encountered the problem as well! Somehow the session which is used to create the app password is never properly closed, and is reused on a new login! I need to figure out how I can circumvent that!

**Comment by Teifun2** [comment]
I'm working on this issue. It has to do with the login flow which I currently use.

For the time beeing there is a workaround.
Go to Nextcloud Web - > Settings - > Security
Under the section Devices and Sessions you should see session that belong to your embedded browser that are still active. If you close them you can switch the user.

![Screenshot_20201015_074720.jpg](https://user-images.githubusercontent.com/7461832/96082309-4852ef00-0ebb-11eb-973b-116d69198854.jpg)

**Comment by GutHib** [comment]
Thanks - the workaround did the trick for now.

**Comment by GutHib** [comment]
Just as an fyi - Nextcloud Talk, now in versions 8, has the exact same problem.

Is this pure coincidence, or is it something that should (could?) comehow be fixed in Nextcloud itself?

**Comment by Teifun2** [comment]
It is a problem with the login flow v2 to create an app password. I will probably change the login to use basic auth to quickly create an app password, then this should no longer be a problem. I hope i get arround to do that tomorrow.

**Comment by GutHib** [comment]
Great. If it's ok with you, I'd link up the Nextcloud Talk folks with this thread, hopefully it'll give them an idea what to do.

**Comment by Teifun2** [comment]
So i now changed to the normal login flow
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#converting-to-app-passwords

This resolved the problem for me!
The new version is available as apk here and will soon be on the appstore!

**Comment by GutHib** [comment]
Just a heads up that I've had similar issues with the app again (version 0.5.0). The app kept crashing upon start. To fix the problem, I had to go and delete devices from devices & sessions once again (everything else - update, reinstall, delete cache/data, etc. failed).

I'm probably barking up the wrong tree, but for me, the main reason for using Nextcloud is that I'm in control of my data. It's all on my server, and as long as I have internet and the server is online (and I now my credentials), I should be able to access it. Always. The fact that I was standing in the supermarket today, unable to access the ingredients for tonight's dinner, despite the fact that I had internet and the server was online, isn't a good thing. If there's an actual bug in your app, that's something else - but if your app keeps crashing because the month-old data in some sessions table is screwed up, to me that points to a serious design flaw.

I guess this is something beyond your control, but I'm a bit unsure who to ask, and what to ask for. Is your app connecting to the server directly, or is it utilizing the Nextcloud app? I'm asking because maybe adding a session handling/diagnostics tool to Nextcloud's mobile app could make life a lot easier.

**Comment by Teifun2** [comment]
@GutHib First of all, i'm sorry to hear that the app caused you this much trouble :/

It is very weird to me how the issue you describe could occur. Just to make sure:
 - You removed & installled the app (App was still crashing) (-> I assume you did need to login again?)
 - You revoked the app password and then had to login again? and then the issue was fixed?

I currently have no idea what could have caused this issue :/ 
With the new implementation i do not have any "open" sessions. Each request that i make to the nextcloud-cookbook plugin is "stateless", so i provide the login credentials (with basic auth) for each and every request. Therefore it also does not make sense to me why you would need to revoke one of the app passwords? ;(

**Comment by GutHib** [comment]
No, I didn't remove and install, but instead hit "reinstall" via the Link2SD app. And I ultimately upgraded to 0.6.0. App was still crashing instantly, so I never got to login again.

So removing and reinstalling should have fixed the issue?

I revoked and wiped all the Cookbook App and the related embedded browser entries. No idea if a more selective approach (just revoking the password on just one of them) would have done the trick as well.

What I do know is that I had no problem on the tablet, so it wasn't a general type of problem with accessing Nextcloud on my server. On the tablet I am running version 0.3.8 (which may or may not be relevant).

And that the sessions I killed were months old (which somehow contradicts that there are no "open" sessions). Maybe remnants from previous versions that got in the way?

**Comment by Teifun2** [comment]
Well i'm unsure what the reinstall in Link2SD  does. But if you remove and install the app then i'm sure that all the internal states are "reset" so no previous login information or anything else remains. If reinstalling just installs the current version ontop of the existing, the app state might not be reset.

Ah yes i understand now what you mean by the open session. I assume that you don't use the self generated app password. In this case the first time you login it will create a session to add an app password. This login is then never used again but is not deleted on nextcloud, and i have not found a way to "remove" this session. Maybe i'm using something wrong or the login flow is not yet perfect in nextcloud. 

Sadly its very hard for me to figure out what went wrong / to debug this. The only thing i can do is to keep it in my mind and if i ever have an explanation i can try to fix it :S sorry!

**Comment by GutHib** [comment]
Sounds good, actually. If I happen to run into this problem again, I will test the uninstall/reinstall and report back.

What's the part about the self-generatied app password? When I launch the Cookbook, I'm asked for my login credentials (which I provide). Is there an additional option I'm missing?

**Comment by Teifun2** [comment]
On the same page that you revoked the "sessions" you can also "Create new App Password". You can then use this password as for your login credentials (same username). For this to work you need to select the "Use self generated App Password" options in the Advanced options on the login screen.

The app then does not have to generate its own app password but can use the one you created. The idea of the app password is that the app never stores your actual account password but only the app password. This can be "revoked" / deleted without the need of changing your actual password for the account.
