### ISSUE TITLE
Layout change [suggestion]

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#24]
Since recipes don't wind up on one's own server for nothing, I'm assuming most people already tried out the recipes they add to the Nextcloud cookbook at least once. Which means that in most cases they already know if a recipe is complicated or not. Not a biggie with the web app, where the info for preparation/cooking/total time only occupies one line, but in the android app it takes up half the screen. Personally I wouldn't mind if the that info was simply moved to the bottom of the screen, but if that's not an option, maybe it's at leat possible to condense this part so it only takes up a single line on a typical phone?

```
---------------------------------------
| Preparation |  Cooking  |   Total   |
---------------------------------------
|     0:10    |    0:20   |    0:30   |
---------------------------------------
```

...could do the trick. Thanks!

**Comment by Teifun2** [comment]
I implemented something similar now.
The times are still individual "boxes" but they are only as wide as they need to be. This should result on most devices in a similar experience as you suggeted. 
But on very slim devices / Or in translations where this strings are very long. It is still possible to place them under each other.

Should come with next release.
