### ISSUE TITLE
App triggers server alarms

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#25]
There seems to be another problem with the app, in that it uses too many connections. When I click to view a list of 33 recipes, I get blocked by my server. Reason: IP is found to have 33 connections.

I understand that I could unhinge some security measures on my server to get around this, but since the app is targeted at folks running their own servers, it probably won't take long until the next guy runs into issues.

I'm afraid I know zip about programming apps, but I do have experience with mysql and php, and there it's a matter of progam architecture if you chose to reuse your threads or start a new connection for every image.

Any chance the architecture of your app could be improved to mitigate this issue?

**Comment by GutHib** [comment]
UPDATE: My firewall limits were probably set too low, so I raised them. It remains to be seen if the problem reappears as I add more recipes to the database - if it does, I'll update this ticket.

**Comment by Teifun2** [comment]
So i updated the way the http client is handled slightly with version 0.3.5. and it should now no longer create a client for each request of json data.

For the images it is more complex as i use a existing widget CachedNetworkImage which does not expose the http client. Therefore i would need to implement my own if it remains an issue.

Would it be ok for you if we close the issue for now and if the issue arises again i can try to investigate further?

**Comment by GutHib** [comment]
Sure. Like I said, I did raise the limits on my end as well, so with your tweaks as well, I'm confident there will be no trouble in the future. Thanks!
