### ISSUE TITLE
IDNs not understood

### ISSUE THREAD

**Issue by qoheniac** [Teifun2/nextcloud-cookbook-flutter#26]
The app does not work with IDNs as server addresses. Punycode works, but it would be nice if IDNs are accepted directly.

**Comment by Teifun2** [comment]
Could you provide me with an example so that i can debug that?

**Comment by qoheniac** [comment]
If you write me an [email](mailto:qoheniac@pm.me) I will send you credentials for a Nextcloud instance with an IDN for testing.
