### ISSUE TITLE
[Feature Request] Add dark mode

### ISSUE THREAD

**Issue by Thovi98** [Teifun2/nextcloud-cookbook-flutter#29]
Hello @Teifun2,
Thanks a lot for your app which makes it a lot simpler to see my recipes, and it’s already soo good !
I know it’s certainly not the priority, but I would be very happy to see a dark theme on this app.
Thanks again for this app. If I can help on a way or another (more on testing, as I’m not a developper), I would be glad to help you 😃

**Comment by Teifun2** [comment]
Hello @Thovi98 

Firstly thanks a lot for your kind words,
About the dark mode i will investigate, maybe there is a simple flutter way to achieve this whithout major changes!

Otherwhise this will need to wait a bit, but i like the idea!

**Comment by florian-hild** [comment]
Darkmode would be very nice. If you have no image for your recipes you can't read the white names of the Categories.
![Screenshot_20210117-003338](https://user-images.githubusercontent.com/47560194/104827235-ced0f100-585b-11eb-88f7-9e084efa7b57.png)

**Comment by Teifun2** [comment]
@florian-hild This is very weird. The behaviour should be differently if there is no image for a recipe!

Are you on the newest app version and plugin version on nextcloud?

See:
![Screenshot_1611071040](https://user-images.githubusercontent.com/7461832/105057851-ec79a280-5a75-11eb-9b31-fd401b3ebb6a.png)

**Comment by Teifun2** [comment]
@florian-hild With the other bug i was investigating i also came across this problem! I will be able to hopefully solve this soon! Sorry for the cirumstances!

**Comment by Teifun2** [comment]
@florian-hild  With the new version this should no longer happen!

**Comment by florian-hild** [comment]
Thank you! Now it's looking fine.

**Comment by Thovi98** [comment]
Thanks for the support !
Looks beautiful now 😊
