### ISSUE TITLE
Server URL -> Cannot reach

### ISSUE THREAD

**Issue by cbartels2** [Teifun2/nextcloud-cookbook-flutter#30]
If you have a Nextcloud running on a custom port, f.e. https://cloud.nexcloud.com:55840 the app fails to connect after typing in the Server URL. Message "Cannot reach https://cloud.nexcloud.com:55840".

Android 8.0.0
Nextcloud 19.0.5

**Comment by Teifun2** [comment]
Could you create a test account for me?
I have no runing nextcloud server that uses a port and it would be a hassle to setup one to test / debug this!

**Comment by cbartels2** [comment]
Is it possible to send you an PM for login data?

**Comment by Teifun2** [comment]
https://matrix.to/#/#nextcloud-cookbook:matrix.org

The easiest way would be to contact me in the matrix chat of the cookbook app. You can send me a pm there my name is Teifun2!

**Comment by Teifun2** [comment]
It seems to be a certificate issue of your server which is currently nothing that i can handle.
I have written you a kor thourugh explanation over the PM.

**Comment by cbartels2** [comment]
It's a certificate issue, thanks to Teifun2!
You need to install the fullchain, here f.e. in apache2:

`SSLCertificateChainFile /path/to/certificate/fullchain.crt`
