### ISSUE TITLE
App stuck after being granted access

### ISSUE THREAD

**Issue by abers** [Teifun2/nextcloud-cookbook-flutter#31]
After logging in and granting access the app doesn't do anything. It just sits on the access granted page saying I can now close the window. Nothing happens even after 10+ minutes waiting. Force closing the app and opening it again goes back through login process and gets stuck at the same point. Also hitting back after access granted page just gives a token error page instead.

**Comment by Teifun2** [comment]
I had multiple issues about a similar behaviour.
I just published a new version which should hit the google play store tomorrow? (i hope)

In this new version i changed the login flow to no longer work with this authorization page.
I now uses the username + password to create an app passsword as promoted by the nextcloud api
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#converting-to-app-passwords

Please let me know if this change fixed your problem!
