### ISSUE TITLE
 default categories view doesn't show categories

### ISSUE THREAD

**Issue by jhaar** [Teifun2/nextcloud-cookbook-flutter#35]
Description
When I view my nextcloud-20 Cookbook, I can see icons for each Category with the number of recipes in each - but there's no mention of the category name. I end up having to guess - clicking on each in order to find out what is inside it

This is the Android NextCloud Cookbook "Teifun2" version just installed today

BTW looking at the Cookbook app within the web browser shows images, etc - so the backend is working correctly. Interestingly the browser interface defaults to "All recipes" and doesn't really have a "show categories" option like this Android app is doing - which is a pity as that's a good idea :-)

Reproduction

    start app
    see bunch of icons with no details except for the number of recipes

Expected behavior
should at least see the Category name - perhaps with mixture of the recipe images?

**Comment by Teifun2** [comment]
Hello and thanks for reporting this bug!

This seems very weird to me. The Category name should be on the "card" and also one thumbnail of the first recipe in this category.

Is it possible that you have a special language characters in your recipe names? Would it be possible for you to create a test account for me with some sample recipes that show the same behaviour? With this i could properly debug the issue and try to figure out what is wrong!

You can contact me on the matrix chat of the nextcloud/cookbook https://matrix.to/#/#nextcloud-cookbook:matrix.org

**Comment by Teifun2** [comment]
Maybe this issue is related to #37 ?

**Comment by Teifun2** [comment]
There is now a new version of the app. Can you check if your issue still persist. If it does i would need more information to help you!

**Comment by jhaar** [comment]
That fixed it! It still showed no images, then I went into Google Play, saw the update - installed it, and now it shows the images. thanks!
