### ISSUE TITLE
Category Load Failed

### ISSUE THREAD

**Issue by winst0nsmith** [Teifun2/nextcloud-cookbook-flutter#39]
great work, your app looks promising, but i can't get it to work...

after opening the app and pointing it at my nextcloud server, the app connects, the categories in my cookbook are momentarily visible, with some spinning red circles (i suppose it is refreshing?)

it immediately errors out tho.

<code>Category Load Failed: Dio Error [DioErrorType.DEFAULT]: SocketException: OS Error: Connection refused, errno = 111, address = nextcloud.myserver.org, port = 45546</code>

any hints?

**Comment by RlndVt** [comment]
I receive the same spinning circles, but error into:

    Category Load Failed: Bad state: No element

If I refresh the recipes and select one of the spinning circles I open the correct category.

**Comment by Teifun2** [comment]
@winst0nsmith could you provide me with a test account to check this out? (linard.schwendener@gmail.com)

@RlndVt Maybe you check #37 as there seem to be more people having your issue!

**Comment by RlndVt** [comment]
I added a recipe (from URL) and removed my test recipes and suddenly the app works fine...

**Comment by Teifun2** [comment]
@RlndVt Hmm that is weird. Some data issue in that case. But great that it works for you!

**Comment by Teifun2** [comment]
@RlndVt I was able to reproduce / fix this issue as it had to do with missing images and the app not behaving well wen no image can be found!

@winst0nsmith Please let me now if version 0.3.8 fixed your problem!
