### ISSUE TITLE
i18n: Amendments

### ISSUE THREAD

**Issue by Valdnet** [Teifun2/nextcloud-cookbook-flutter#40]
- If you use PR: #38 you must add spaces in the code between "Servings:" and 

https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/3d13f34f3acd180a8f591b2988af1bc972ba5b34/lib/src/screens/recipe_screen.dart#L134

- "source": "Source:"
If this string text is present on the button and in the information, it should be duplicated as now the colon on the button will be displayed.

**Comment by Teifun2** [comment]
Thanks. Will add the necessary changes!

**Comment by Teifun2** [comment]
Have added these changes to the new bugfix changes!
