### ISSUE TITLE
[Feature request] Keep the screen on

### ISSUE THREAD

**Issue by GutHib** [Teifun2/nextcloud-cookbook-flutter#41]
Hi,

It would be great if this app had a button to keep the screen from going out. I believe the benefits are easy to see: Less grease/batter/sauce/flour stains on the device. :)

Thanks!

**Comment by Teifun2** [comment]
Oh that's actually a good idea ^^
I need to find out how that works on a technical side! If it's easy then I will do it soon!

**Comment by GutHib** [comment]
Nice.

**Comment by Teifun2** [comment]
This was delivered :)
