### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by sepo83** [Teifun2/nextcloud-cookbook-flutter#43]
Could you publish the app on F-Droid? 
I would offer some help with creating the necessary metadata-files in this repo and in the fdroiddata repo.

**Comment by Teifun2** [comment]
@sepo83 That would be much apperciated. I'm currently only offering the app over the alternative location (IzyyOnDroid) as you can see in the readme! This is to my knowledge similar to FDroid but i did not need to go through the process of applying for the fdroid process!

I have not found time to do this as it is for myself not a priority but if you would help me with that i would very gladly take it :)

**Comment by sepo83** [comment]
You are  right FDroid consists of several components. [fdroidserver](https://gitlab.com/fdroid/fdroidserver) can be run by anyone providing a fdroid repository. One can either put pre-build apks in it or choose to build them from source. The official FDroid repo only builds apps from source and signs the apks with own keys. The official FDroid repo is managed in [fdroiddata](https://gitlab.com/fdroid/fdroiddata). A new apk can be added with a merge request adding a yml-file that contains general metadata and build instructions. Further metadata (like changelog, description, screenshots, etc) is recommended to stay in the repository of the app using fastlane- or Triple-T- structure.


So far I prepared most things. I would suggest the following steps:
1. check the fdroiddata metadata file I have prepared (https://gitlab.com/sepo83/fdroiddata/-/blob/master/metadata/com.nextcloud_cookbook_flutter.yml)
    * esp. check metadata like Categories, License, AuthorName, SourceCode, etc
    * check build instructions --> with this I can build the app locally and the gitlab pipline of my fdroiddata fork also suceeds     
2. accept my PR https://github.com/Teifun2/nextcloud-cookbook-flutter/pull/47 that initially adds metadata in fastlane-structure
    * make sure  you keep this up to date, esp. changelog of new versions (add a txt file with the version-code as name (`<versioncode>.txt`) and the changes for that version as content to `fastlane/metadata/android/en-US/changelogs`.)
    * optionally other languages can be added (later)
2. make a new release that includes the metadata from step 2 and come back to me
3. I will adapt the `com.nextcloud_cookbook_flutter.yml` for frdoiddata to the new release from step 3
4. Finally you should do the merge-request to the fdroiddata-repo with the following steps:
    1. fork the fdroiddata repo from https://gitlab.com/fdroid/fdroiddata
    1. add `metadata/com.nextcloud_cookbook_flutter.yml` from my fork https://gitlab.com/sepo83/fdroiddata
    1. optionally redo the steps fdroid supposes at https://gitlab.com/fdroid/fdroiddata/-/blob/master/CONTRIBUTING.md --> However, this is what I have so far :smile: 
    1. check the gitlab pipeline output of your fdroiddata-fork
    1. do a merge request to the original fdroiddata repo 
        * make sure you give them write acess to your merge request
        * they will do a review of your app
        * after it is merged your app will be published with the next scheduled build-run on fdroid 
 5. New releases will be automtically published on fdroid. For this fdroiddata regulary extracts the latest version from pubspec.yml (master-branch) and looks for a git tag with this version.

**Comment by Teifun2** [comment]
Wow that looks very good already!

1. Done!
2. Can i merge it to Develop? (I like to have only released states on master, just a habit ^^)
3. With release you mean APK? Or do i need to increase the version number for that?
4. Clear
5. I think i understood all the steps, but lets check when we are that far!

**Comment by sepo83** [comment]
Please do a complete release with my changes e.g. to 0.3.9+15 (or something). I think fdroid will look at a tagged release for the metadata from the fastlane structure.

**Comment by Teifun2** [comment]
Soo, sorry it took some time until i got around, but it is done now. 

0.3.9+15. I updated the screenshots (made some new ones) added the changelog file and updated the full_description.

So as soon as your for is updated i will "duplicate" your fork and check if the pipeline works properly. If yes i can create a pull request. 
Have i understood that correctly? :D

**Comment by sepo83** [comment]
No problem at all... I have update the version number and it successfully built locally and within the gitlab pipeline on my fork. 

Yes, you got it correctly ... ;-)  You can go on as you have written...

BTW, make sure you give the fdroid team write access to your merge request.

Many Thanks for your great app!

**Comment by Teifun2** [comment]
Ok i now forked fdroid and added the metadata file as you described. Its currently running the pipeline.

I now also have a new version coming up of my app 😃  i hope this does not pose a problem, but if i understood you correctly then they will automatically start pulling the new versions.

Last but not least, do you mean giving them write access to my fork repo? I have never seen that i can give write access to a merge request but it is possible that i dont know how 😄

**Comment by sepo83** [comment]
I don't think that the upcomming new version is a problem. Might be that they initially add the current version and a few days later update to the upcomming version.

On the gitlab merge request there is an option "Allow commits from members who can merge to the target branch. About this feature. Not available for protected branches"

**Comment by Teifun2** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8290

well then lets see what happens :)

**Comment by sepo83** [comment]
@Teifun2:
I have seen, that the fdroid team had some findings with the merge request. Do you need help for fixing them?

**Comment by Teifun2** [comment]
@sepo83 
Indeed i have seen their findings. Sorry i had a busy week and last weekend and was therefore not able to do much. 
I Updated the YML according to the findings. (I hope i did everything correct :D)

**Comment by Teifun2** [comment]
@sepo83 Thanks to your help this seems to be finished. I dont know if the app is already appearing but it should be that way very soon! Thanks a lot!!
