### ISSUE TITLE
[Feature request] Text slightly uncomfortable to read

### ISSUE THREAD

**Issue by JoshuaPettus** [Teifun2/nextcloud-cookbook-flutter#44]
First of all, let me say this app is off to a fantastic start, and I'm absolutely loving it.  Excellent job!  

One thing though, I kinda find the current font/size just slightly uncomfortable to read particularly in recipe instructions and ingredients , if there were a way to increase the size just slightly?  I know it's such a balancing act putting so much text on so little real estate such as on a phone, plus every phone is different.  Maybe simply a different, slightly thicker, font would go a long way to make it more readable?  Helvetica Now, or something like it. Not sure what opensource fonts you can use. Google Open Sans maybe?   I know darkmode, which is already on your list, would help a lot in this department too.

Thank you!

**Comment by Teifun2** [comment]
There is also another issue with Category font. I need to find a good way to add settings for this. When there will be local settings (like dark mode etc.) it might just be possible to add different "font-sizes"

**Comment by fab920** [comment]
I would advice against offering an option for font sizes. If something is not readable, is a problem with the UI and the UI should get fixed.

Are any other (popular) apps offer the option to change the font size?

**Comment by Teifun2** [comment]
@fab920 Generally i agree with you. What do you think would be the better way to progress? I can see that it during cooking the recipe instructions could maybe be a little bigger. But currently its just the default size, (and i have the settings which can change recipe text running)
