### ISSUE TITLE
Cooking / Total Time Values Displayed Incorrectly

### ISSUE THREAD

**Issue by jnikolich** [Teifun2/nextcloud-cookbook-flutter#49]
NextCloud Version: **20.0.5**
Cookbook Plugin Version:  **0.7.10**
Mobile Client Version: **0.3.8**

Two of the thee various times (Cooking, and Total) appear to be getting incorrectly calculated or pulled from NextCloud.  The Preparation time appears to be correct.  This has been tested with 3 separate recipes.

As an example, one of my recipes displays *(correctly)* the following times within the NextCloud App plugin in the NextCloud web-interface:
```
Preparation time:  15:00
Cooking time:      25:00
Total time:        40:00
```

However in the mobile client, the same recipe displays the following times:
```
Preparation time:  15:00
Cooking time:       1:00
Total time:        16:00
```

Other than that, so far the mobile client is pretty awesome - simple and easy to use!  Thanks!

**Comment by Teifun2** [comment]
Ah shit ^^ i see my mistake here.

I expected no recipe to take longer than 24 hours and for some stupid reason i then calculate the hours "modulo" 24. So only the remaining will be displayed.

I will fix that for the next release!

**Comment by Teifun2** [comment]
That is solved in the new version!

**Comment by jnikolich** [comment]
Confirmed that it now displays properly.

Thanks also for the chance to learn something myself:  I thought the times were MM:SS, not HH:MM.  I'll have to go in and fix those in my recipes.

Thanks again!
