### ISSUE TITLE
[Feature request] Multiple sections in an ingredient list

### ISSUE THREAD

**Issue by teemue** [Teifun2/nextcloud-cookbook-flutter#50]
Many recipes would be clearer to write and especially to read if the ingredient list had an option to add labeled sections ([example](https://www.allrecipes.com/recipe/276887/copycat-fried-chicken-sandwich/)).

**Comment by Teifun2** [comment]
To my knowledge this feature is not yet available in the nextcloud/cookbook plugin? If this is the case you need to request this feature over in their github repo.

My app is only a client to display the info's that the nextcloud plugin also contains!

**Comment by teemue** [comment]
You are right, sorry for the inconvinience :) I posted this request on nc/cookbook !
