### ISSUE TITLE
editing-page not shown correctly

### ISSUE THREAD

**Issue by inos-github** [Teifun2/nextcloud-cookbook-flutter#55]
if there is one of the three time fields (prepTime, cookTime, totalTime) missing, the editing page is not showing up correctly. All fields after the time fields are missing as s well as the update button.

**Comment by Teifun2** [comment]
Thanks for reporting this issue.

Im already working on a fix for that and hope that i can publish a fixed version on the weekend!

**Comment by goebbe** [comment]
Thank you very much for adding editing!!
For some of my recipes editing seems to work fine. 
If required, I could provide examples of recipes that work o.k. and that do not work for all fields (just a grey box is shown).

**Comment by goebbe** [comment]
[edit_not_for_al_fields_recipe.zip](https://github.com/Teifun2/nextcloud-cookbook-flutter/files/6217416/edit_not_for_al_fields_recipe.zip)
[editing_ok_recipe.zip](https://github.com/Teifun2/nextcloud-cookbook-flutter/files/6217417/editing_ok_recipe.zip)

**Comment by Teifun2** [comment]
I fixed some issues around cooking etc times. 
Could you check if the Problem still exists in version 0.6.0?

**Comment by inos-github** [comment]
As far as I can see it's fixed

**Comment by Teifun2** [comment]
Thats great to hear. In this case i will close the issue! 
Thanks for your feedback!
