### ISSUE TITLE
IOs Release

### ISSUE THREAD

**Issue by TheMBeat** [Teifun2/nextcloud-cookbook-flutter#58]
Is an IOs release planned?

**Comment by Teifun2** [comment]
This is definitely the plan.

The problems are:
- Currently i have no Mac OS development machine to test (Maybe i try and setup a vm for this)
- I have no Apple Developer account. Ideally someone else with an active account would "publish" the app, as the account costs money and i'm not willing to pay yearly fees to provide a free app.

**Comment by TheMBeat** [comment]
That sounds good. 

- If the source code for IOs is available, anyone with a Mac can compile the app themselves. 

- I don't have a developer account either.Who publishes the other Nextcloud apps for IOs, they could possibly publish the Cookbook client as well.

**Comment by Teifun2** [comment]
@TheMBeat The source code is in this project. With flutter you are supposed to be able to compile it directly for IOS.
There might be some compatability issue but in theory it should work. But so far i have never tested it.

To check with nextcloud publishers is actually not a bad idea!

**Comment by Dominik-Tils** [comment]
Any progress yet?
Haven’t done iOS development yet but would like to give it a try and help out.

It seems like you don’t need a Mac anymore m for iOS development to get startet:
https://dotnet.microsoft.com/apps/xamarin/mobile-apps
Have you tried that already?

**Comment by Teifun2** [comment]
@schlagmichdoch 
No so far there has no been progress on this, I was rather busy and was not able to work much on this project.

If i understand it correctly xamarin is similar to flutter as it allows cross platform. I don't think that this project will ever switch to another technology, as Flutter can be compiled to iOS apps already. For the compilation however a mac is needed. I plan to test this soon with a VM.

**Comment by meichthys** [comment]
@Teifun2 Have you had a chance to try this via a VM? If not, I run MacOS and would be willing to try to compile it if I had a little bit of help. I've compiled apps before but nothing related to Flutter.

**Comment by Teifun2** [comment]
Hi @meichthys

No I had not time to tackle this so far.

If you could start with that this could be awesome! If you need any help with specific flutter questions and I can try to help, but generally I would just recommend to follow official flutter installation. And then trying to run the app.

If you join the matrix chat of the nextcloud cookbook community you can find me there / contact me there!

**Comment by meichthys** [comment]
Update: This is coming along nicely, but we do have a few things to work through. Right now notifications are not working which also currently breaks the timers, but the main functionality of the app does work quite well!

![image](https://user-images.githubusercontent.com/10717998/146655140-207a7f23-e4c7-46a5-bbe8-4f060bba4fef.png)


![image](https://user-images.githubusercontent.com/10717998/146655124-7df67d25-94dd-42f1-9eda-889db6c5442c.png)

**Comment by meichthys** [comment]
As for releasing to the App Store, it looks like the only iOS app that is released by Nextcloud themselves is the Talk app. All the others including the official nextcloud app are released under personal developer accounts.

**Comment by TheMBeat** [comment]
Hi @meichthys, 
what is the status of an IO releases?

**Comment by meichthys** [comment]
@TheMBeat I have a working build but it's based on an older version. I can re-build this week to see where we are at. Currently notifications and timers are broken in the iOS build, but I can see if that's still the case on the latest.

**Comment by meichthys** [comment]
Just an update here,

I tested off the latest master branch and things are still working nicely. The two main issues that i can see are:

- Notifications are broken and need to be disabled for the ios build
- Timers do not work for the ios build (perhaps due to notifications being disabled?)

**Comment by TheMBeat** [comment]
I think everyone can live without notifications for now. Now we just need someone to publish the app.

**Comment by j-koreth** [comment]
Hello everyone, 
I have a Mac and a developer account to publish apps.  
I have a decent amount of experience with flutter I'll take a look at the getting the project building and possibly publishing.

**Comment by meichthys** [comment]
@j-koreth Are you available this evening? I have a Running build that I can show you.

**Comment by j-koreth** [comment]
Hi @meichthys i should be free tomorrow evening. Feel free to email me

**Comment by TheMBeat** [comment]
Hey @j-koreth, I'm looking forward to the test, if Testflight is to be used I'm in. 
I think the app should be released for both IOs and IPadOs.

**Comment by meichthys** [comment]
@TheMBeat  yes, once we have a release, it will be available on all iOS devices 👍

**Comment by Teifun2** [comment]
@j-koreth 

Hello. It would be aswesome if we could get this app running on IOS aswell!

For me it is fine whoever publishes it. I think the only condition would be that it stays free and without ads.

**Comment by j-koreth** [comment]
https://testflight.apple.com/join/leE86yyq

**Comment by Teifun2** [comment]
@j-koreth This is awesome! I tried it out and it works very well! Thank you very much.

Do you have any plans or roadmap?

Do you think there is a need for a Chatroom to be opened, so that contributers can coordinate better?

**Comment by j-koreth** [comment]
@meichthys have talked through matrix and have joined the nextcloud cookbook room but I am down to join anything to talk about this. @Teifun2 email btw to talk about further publishing.

**Comment by j-koreth** [comment]
I plan to publish it at some point just need to get around to getting everything prepped for it.

**Comment by meichthys** [comment]
> Do you think there is a need for a Chatroom to be opened, so that contributors can coordinate better?

Unless you think differently, we can probably share the main matrix chatroom for now too keep things simple.

**Comment by j-koreth** [comment]
That works for me.

**Comment by Philipp5796** [comment]
The testflight app will expire 90 days after uploading, which is in three weeks. 
@j-koreth  I think it would be time to publish the app to the app store ;)

**Comment by meichthys** [comment]
Agreed. I've tested it for a while and found it to be quite stable and functional 👍
@j-koreth let me know if there's anything you would like me to help out with.

**Comment by djcath** [comment]
Is there anything that anyone can help with to get this across the line?

**Comment by djcath** [comment]
@j-koreth making any headway? 8 days left in test flight and I’m anxiously hoping this can get published as it’s such a good app.
I’m no dev, but if I can help in anyway let me know

**Comment by j-koreth** [comment]
Hey guys sorry for the delays I'll get to work this weekend to try to get into the App Store. Will update if there's any other issues.

**Comment by djcath** [comment]
@j-koreth  I thought I’d try my luck and attempt a side load with free dev account to my phone with 0 knowledge and experience in Xcode.  Turns out it’s not as simple as it sounds 😂 I’ll just climb back into my box

**Comment by TheMBeat** [comment]
Any new News? Because TestFlight Beta is expired?

**Comment by djcath** [comment]
If I knew even the smallest thing about packaging apps I’d do it just because I’m that desperate to have this.

**Comment by j-koreth** [comment]
Taking a look into release

**Comment by meichthys** [comment]
@j-koreth Any progress on the release? Once it's live, we can as iOS to the main cookbook repo's readme: https://github.com/nextcloud/cookbook/edit/master/README.md

**Comment by j-koreth** [comment]
Had some issues with my dev environment I think I resolved most of it sorry for the delay everyone

**Comment by meichthys** [comment]
We're rooting for you!

**Comment by djcath** [comment]
Hope all is good. At the very least could we maybe get another TestFlight in the mean time?

**Comment by j-koreth** [comment]
Yes that’s what I’m working on. For some reason the app connect is rejecting the Xcode beta builds but I’ll work on resolving that as the first priority.

**Comment by djcath** [comment]
Awesome, I wish I knew how to even do any of this. When I attempted your build myself I got an error about pods and my mind just blew into a million pieces

**Comment by j-koreth** [comment]
Can everyone check if a build is available on test flight?

**Comment by meichthys** [comment]
TestFlight looks good 👍

**Comment by djcath** [comment]
Test flight has 91 days remaining now!

**Comment by Philipp5796** [comment]
iPhone X looks good. 
iPad 2 with IOS 9.3.5, where the old Build worked without problems, is now displayed as not supported device in Testflight with this Build

**Comment by TheMBeat** [comment]
iOS 16 on iPhone X works well, too.

**Comment by j-koreth** [comment]
@djcath Is that different in iOS vs android? 
@Philipp5796  I'll see what I can do

**Comment by djcath** [comment]
@j-koreth seems specific to the ios app.

**Comment by djcath** [comment]
@j-koreth  Just raising that the current iOS build is still referencing the Cookbooks old API endpoints so launching recipes shows a 405 error.  This is said to be resolved in @Teifun2 newest build for Androids?

**Comment by j-koreth** [comment]
@Teifun2 Is there a pipeline to generate the apks automatically right now? 

I'll update the iOS TestFlight version in the mean time

**Comment by j-koreth** [comment]
The TestFlight should've been updated

**Comment by djcath** [comment]
@j-koreth can confirm the new build works on the latest cookbook plugin version.  FYI though,  newest build is not backward compatible to plugin version 0.9.13.

**Comment by Teifun2** [comment]
@j-koreth Sadly i have no pipeline for this yet. but it is defenitively on the todo list :)

**Comment by j-koreth** [comment]
Uploading for app review

**Comment by j-koreth** [comment]
https://apps.apple.com/us/app/nextcloud-cookbook/id1619926634

**Comment by j-koreth** [comment]
@Teifun2 If all goes well maybe this can be closed and a link can be added to the README

**Comment by djcath** [comment]
@j-koreth  amazing work! 
just pulled down from App Store and working (australia)

**Comment by meichthys** [comment]
> https://apps.apple.com/us/app/nextcloud-cookbook/id1619926634

@j-koreth great work!
So far everything seems to be working as expected.

**Comment by Teifun2** [comment]
Awesome this is great to hear!

**Comment by meichthys** [comment]
@TheMBeat I think we can close this now!

**Comment by Teifun2** [comment]
@j-koreth  Thank you very much for putting it into the app store, that is awesome!

I will close this now as there is an iOS release. Potentially we have to see how we can streamline new versions in teh future, but the first step has been made!
