### ISSUE TITLE
Doesn't display recipes if durations are null

### ISSUE THREAD

**Issue by languitar** [Teifun2/nextcloud-cookbook-flutter#61]
The auto imprt feature of the nextcloud cookbook app sometimes creates recipes where `prepTime` or other duration fields have a `null` value. The app errors out on these recipes. Some tolerance against such cases would be nice.

**Comment by FrauNahtig** [comment]
Same issue on my side. For a short term workaround, I replaced all occurrences of ':null,' with ':"",' in the jsons-recipes directly.

**Comment by Teifun2** [comment]
This should be fixed with the new version 0.6.0. Please let me know if it now works on your side!

**Comment by languitar** [comment]
Is this version already going through the F-Droid release process? I can check that once it is available on F-Droid.

**Comment by FrauNahtig** [comment]
It works fine for me. Tested with the Release (apk) 0.6.0 from this site. Thanks a lot.

**Comment by Teifun2** [comment]
@languitar yes the new version should automatically come to F-Droid.

I'm actually a little unsure why it takes more than one night but i must admit that i didn't fully understand the process.
Version 0.5 was available automatically after some time!

**Comment by Teifun2** [comment]
And as it seems to work now i will close this issue now! 

If it doesent for you @languitar dont hesitate to comment so we can reopen this.
