### ISSUE TITLE
Expand ingredients list on recipe open

### ISSUE THREAD

**Issue by eht16** [Teifun2/nextcloud-cookbook-flutter#63]
Great app, thank you!

I personally would prefer to have the ingredients list to be expanded, and so visible, directly when opening a recipe.
Usually, the list of ingredients is the first thing I'm interested when viewing a recipe.

Could there be a setting or it just be expanded by default?

**Comment by Teifun2** [comment]
Hey thanks for the kind words and the improvement suggestion.

I've been thinking a while about adding a simple settings page with all kinds of small detail settings. As soon as I have the settings page created adding this specifically will be no problem!

There is also a flutter package that helps with creating settings pages so this might go relatively fast. I will check next time I work on the app!

**Comment by Teifun2** [comment]
i changed my mind about this. I think Ingredients should be visible by default as you suggested! I will change it this way!
