### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by EvaFuchs** [Teifun2/nextcloud-cookbook-flutter#64]
When I try to search in main menu for a recipe I always get result "recipe not found". Attached you can see my category "Kuchen" with 3 recipes -  none of them could be found :(
![category Kuchen](https://user-images.githubusercontent.com/83494283/116777118-eaf44900-aa6c-11eb-9a94-0cdf76e2004b.jpg)
![Rhabarberkuchen_SearchFailed2](https://user-images.githubusercontent.com/83494283/116777121-f21b5700-aa6c-11eb-8e16-93d9db2c066b.jpg)
![SearchFailed](https://user-images.githubusercontent.com/83494283/116777122-f2b3ed80-aa6c-11eb-8a34-ed9395544d1c.jpg)

**Comment by Teifun2** [comment]
Hmm this is strange. I need to retest on my device to check. If i cannot reproduce it i might need some more information!

**Comment by Teifun2** [comment]
I'm not able to reproduce this :/ 
Can you maybe provide more information?
Such as:
- Nextcloud Version
- Nextcloud Cookbook Version
- Android Version
- Recipes would also be helpful (as a zip or similar)

**Comment by FrauNahtig** [comment]
Same Problem here:

Nextcloud Version: 20.0.9
Nextcloud Cookbook: 0.8.4
App-Version Nextcloud Cookbook: 0.6.0 
Android: 11

**Comment by EvaFuchs** [comment]
Nextcloud Version 19.0.9.1
Nextcloud Cookbook: ?? coming soon
App-Version Nextcloud Cookbook: 0.6.0 - just installed, error remains :(
Android: 9

**Comment by Teifun2** [comment]
Hmm 🤔 very weird!
Could somone provide me with a zip of the recipes that are not working with the search (or even better a test account on the specific instance with the recipes setup?)
( linard.schwendener@gmail.com )

**Comment by redseasix** [comment]
Gleiches Problem suche nicht möglich
Software Versionen:
Android 10
nextcloud 21
Cookbook 0.6.0

Verwendete Rezepte:

https://www.chefkoch.de/rezepte/2926511444998465/Buletten-mit-mediterranem-Kartoffelsalat.html

https://www.chefkoch.de/rezepte/81091031742662/Rote-Linsensuppe.html

**Comment by saschamander** [comment]
Any updates on this?
I have the same issue
Nextcloud 22.2.3
Cookbook 0.9.8
Android 8.0

Apart from that everything seems to be working as intended. Really like the app. Keep up the good work.

**Comment by patterchon** [comment]
I have the same issue ...
Nextcloud 22.2.3
Cookbook app 0.9.9
Nextcloud cookbook app version 0.75
Android 11 and /e/OS on Fairphone 4

**Comment by zorglubu** [comment]
First, thanks for your nice app. I just miss the search function as well.
Nextcloud  23.0.2
Android 11 and /e/OS on Fairphone 3
cookbook app version 0.7.6 f-droid

Would you like a shared link to my recipes in order to download a zip ?

**Comment by Teifun2** [comment]
@zorglubu 
Thanks for the info. I think this issue is not related to recipes but how the System behaves. I need to figure out how to reproduce this but have not been able to manage so far. (or rework the search which i did not get around to do yet)

I'm sorry for the issue 😢

**Comment by hendrik-hog** [comment]
Hey @Teifun2, I also faced this bug and took a look into it. I was able to solve it. Please have a look at reviewing the PR I created if you like.

**Comment by Teifun2** [comment]
@hendrik-hog This was such a stupid simple problem i cannot belive it :D thanks a lot!
