### ISSUE TITLE
Offline Usage / Caching

### ISSUE THREAD

**Issue by maxolasersquad** [Teifun2/nextcloud-cookbook-flutter#65]
This app currently does not work if you are not connected to the Internet, or the Nextcloud server is down. It would be cool if the app loaded data from the cache and created a background job to update the cache on startup.

**Comment by Teifun2** [comment]
Hello and welcome :)

Yes this would indeed be a nice feature and is planned. I wanted to get all the basic functionality down before tackling this. But i think i will soon start to think how to achieve this!

**Comment by Teifun2** [comment]
I just noticed this duplicate #48 so i will close this issue to clear up the tasks!
