### ISSUE TITLE
Import Failed Exception

### ISSUE THREAD

**Issue by JoshuaPettus** [Teifun2/nextcloud-cookbook-flutter#67]
When I try the Import feature, I get a red screen that comes up with Import Failed Exception, and followed by a bunch of html header stuff.

This also happens when I don't put anything in the url field.  Shouldn't there be a nice error like "field empty" or if the site can't be parsed say something like that?

It will only appear for a second and then go away.  I managed to take a screenshot

Here is the link I tried to import
https://heygrillhey.com/grilled-pork-loin/#wprm-recipe-container-11636

<img src="https://cloud.joshpettus.com/s/k37RFjQqXFdaJKS/preview" alt="error" width="300"/>

**Comment by JoshuaPettus** [comment]
Actually It may be a problem with the Cookbook App itself.  When I try to import it through the regular web interface, I get a blank box that pops up and just ok....  you wouldn't happen to have any advice for that?  In anycase it's starting not to look like a bug with this app.

**Comment by JoshuaPettus** [comment]
I created a new ticket for the cookbook app side of things.

https://github.com/nextcloud/cookbook/issues/722

I bet once that is working this will work too

**Comment by Teifun2** [comment]
Could you please provide me with the link of the recipe you try to import?
Then I can try to reproduce this issue!

**Comment by Teifun2** [comment]
Ups sorry. I only saw the issue in the mail and didn't realize that you already followed up on that! (I also seem to have missed the link? <- it was early morning :D)

Its definitively a good idea to go to cookbook for that! Thanks for checking!
