### ISSUE TITLE
i18n: Text string in buttons

### ISSUE THREAD

**Issue by Valdnet** [Teifun2/nextcloud-cookbook-flutter#69]
Whether in text strings in buttons:

https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/f680d4e94e6c8789f95e99af719a76d8e5b3d9fc/assets/i18n/en.json#L87-L88

https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/f680d4e94e6c8789f95e99af719a76d8e5b3d9fc/assets/i18n/en.json#L94-L95

do you need the word `Recipe`? The word already appears in the title.

Shouldn't you use the same method as in:

https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/f680d4e94e6c8789f95e99af719a76d8e5b3d9fc/assets/i18n/en.json#L101-L102

**Comment by Teifun2** [comment]
Hmm that's right its a little inconsistent.

I  think we could do it like it is for Import. Do you wanna do the change?

**Comment by Valdnet** [comment]
> Do you wanna do the change?

Yes, I will make a change 😉.

**Comment by Valdnet** [comment]
Done. Please merge 😉.
Additionally, I changed the word `Update` to `Edit`. I think it will fit better here.

**Comment by Teifun2** [comment]
Thanks again for the help! I appreciate!
