### ISSUE TITLE
Sync on images

### ISSUE THREAD

**Issue by xf-** [Teifun2/nextcloud-cookbook-flutter#74]
I replaced a image in nextcloud and one phone the larger image is synced and small one is still the original one and on the tablet no image will update while pressing the Sync arrow button.

**Comment by Teifun2** [comment]
As fab920 mentioned this will be probably fixed with his changes. Whenever i get around to review and merge them 🙈

**Comment by Teifun2** [comment]
Hopefully this will be fixed with the merged #77

**Comment by Teifun2** [comment]
Delivered with 0.7.5 Can you please check if this issue persists? And otherwise open the issue again!

**Comment by xf-** [comment]
> Delivered with 0.7.5 Can you please check if this issue persists? And otherwise open the issue again!

Works for me. Would opt for a different loading indicator. I noticed that mainly in single few on the tablet. The big blue circle while the image is already loaded. Maybe  use the image from listing and replace it (like shops do for fast impression on replace it with a high-res afterwards)
