### ISSUE TITLE
Possibility to logout if server cannot be reached.

### ISSUE THREAD

**Issue by arsocha** [Teifun2/nextcloud-cookbook-flutter#78]
Hi @Teifun2,

First off, thanks for all the work you've done on this project. Fantastic app! 

Offline support would be fantastic; however, this is a slightly different request. I noticed when my phone has no internet / data connectivity the app just starts into a perpetual 'loading' screen, with no way to change options or settings it seem without uninstalling and re-installing the app. 

This is a bit of a niche use case, but I currently have my app set to a LAN only Nextcloud service, but would like to change it to an internet enabled Nextcloud service -- and potentially even switch back and forth as needed. Aside from my niche use case, I think it would generally be a helpful addition to the app to have multi-account support or at least access a settings menu, even with no offline support yet.

Thanks!

**Comment by Teifun2** [comment]
Hello @arsocha 

Thanks for your feedback. I have a few questions!

> the app just starts into a perpetual 'loading' screen, with no way to change options or settings it seem without uninstalling and re-installing the app.

Does this mean even after you gained internet / data you cannot check your recipes without reinstalling? Or is it more if your nextcloud server is down and you want to switch to another this is not possible due to the perpetual loading screen?

> I think it would generally be a helpful addition to the app to have multi-account support or at least access a settings menu, even with no offline support yet.

Multi Account support is definitively something i considered, and want to do at some point. But offline use will be first for sure.
What would you want to have in the settings menu? (Settings menu is already developed but not yet released should come soon with the first settings)

**Comment by arsocha** [comment]
Thanks for the reply @Teifun2! 

To try and clarify for your questions: 

1. The second version is the case! When I have internet (+ obviously access to the nextcloud instance) I can check my recipes again. The issue for me was my nextcloud instance was inaccessible (by design, because I was testing it on an instance that was only setup for a local, non-internet nextcloud deployment) but when I wanted to try and switch to another remotely accessible instance I couldn't because of the perpetual loading screen.

2. Great to hear offline is still in the works, very much looking forward to it. As far as features in a settings menu, really the only major item for me would just be the ability to see / set / re-set the associated nextcloud user credentials (at least prior to loading). I am excited to see what you are working on else wise in a settings menu, but happy to wait and see on that rather than making preemptive comments! 


Thanks!

**Comment by Teifun2** [comment]
> The second version is the case! When I have internet (+ obviously access to the nextcloud instance) I can check my recipes again. The issue for me was my nextcloud instance was inaccessible (by design, because I was testing it on an instance that was only setup for a local, non-internet nextcloud deployment) but when I wanted to try and switch to another remotely accessible instance I couldn't because of the perpetual loading screen.

This is indeed a problem. I will mark this issue as a bug to track this issue.

For part to i will add a Feature Request to track the Multi Account Feature. 

Thanks for your involvemement!

**Comment by arsocha** [comment]
Thanks again for reviewing my concern. Appreciate all you are doing on this project.

**Comment by Teifun2** [comment]
![Screenshot_20211225_171143_com.nextcloud_cookbook_flutter_edit_821152073700742.jpg](https://user-images.githubusercontent.com/7461832/147389153-af5282bc-9ce3-4e9e-aaf8-18fed94493e8.jpg)

**Comment by Teifun2** [comment]
Delivered with 0.7.5

**Comment by arsocha** [comment]
@Teifun2 thanks for all your work on this!
