### ISSUE TITLE
[Feature Request] Import from shared URL

### ISSUE THREAD

**Issue by noctux** [Teifun2/nextcloud-cookbook-flutter#80]
Hey,

first of: Thank you for the really nice app. It helps to keep cooking fun :)

One small thing that I miss is the ability to easily add reciptes from the browser/other apps via "share", though.
The current workflow of copying the url somehow, explicitly opening the app, selecting import from menu, pasting the url, and then import is a bit cumbersome, especially when one is in "recipe exploration mode" :p

So it would be great if the cookbook app could respond to [Android share events](https://flutter.dev/docs/get-started/flutter-for/android-devs#how-do-i-handle-incoming-intents-from-external-applications-in-flutter) for URLs, and hand those over to the import logic.

Thanks again,
Simon

**Comment by Teifun2** [comment]
This is a great idea. I will keep it in mind and try to have a look!

**Comment by Teifun2** [comment]
Delivered with 0.7.5

**Comment by noctux** [comment]
Nice. The release has arrived in F-Droid and it works like a charm! Thanks alot!
