### ISSUE TITLE
i18n: Extract a space

### ISSUE THREAD

**Issue by Valdnet** [Teifun2/nextcloud-cookbook-flutter#84]
You must extract the space from the text string. This will avoid errors when translating a text string in Transifex.

https://github.com/Teifun2/nextcloud-cookbook-flutter/blob/ca11c06c063c92ef0ca17c66a52250144d593108/assets/i18n/en.json#L124

**Comment by Teifun2** [comment]
So just to make sure that i understand you correct. It should eb as follows:
` "finished": "is finished.", `

**Comment by Teifun2** [comment]
Finally got around to fix this. :D that was simple!

Thanks for the input!

**Comment by Teifun2** [comment]
Delivered with 0.7.5
