### ISSUE TITLE
Just a question: de and de_DE

### ISSUE THREAD

**Issue by cloud2018** [Teifun2/nextcloud-cookbook-flutter#85]
Is it necessary to translate ..../i18n/de.json or is only the formal (de_DE) variant used with german language? (In Transifex android-notes, talk-ios, client, ... only strings from de_DE are translated and strings from de are not translated)

**Comment by Teifun2** [comment]
I will close this for now. If you have other questions / input just comment again!

**Comment by cloud2018** [comment]
just for info
With version 0.7.6  the formal (de_DE) language and the informal (de) language are selectable in the settings of the app. Both should be translated

**Comment by Teifun2** [comment]
@cloud2018 
Yes i just noticed a weird behaviour with (de) language for timers. I am unsure how to proceed as transifex itself is generating these different language profiles :/ Do you know more about this topic?

**Comment by cloud2018** [comment]
The text "Benötigt keine Übersetzung. Hier wird nur die formelle Übersetzung verwendet (de_DE)." is the text of the translation, Its not an info of the OS. This standard text  is used to reduce the effort of the translater.
Now all strings from cookbook_flutter are translated (de and de_DE)
