### ISSUE TITLE
Description field should support Markdown

### ISSUE THREAD

**Issue by dmbreakey** [Teifun2/nextcloud-cookbook-flutter#88]
Markdown is supported in the corresponding _Description_ field in the web front-end, so should be supported by the app as well.

**Comment by arsocha** [comment]
I agree this would be a great feature, but I wonder about how that will work for compatibility with recipes displayed in the web interface of NC? 

I currently see a difference between how text and markdown is handled in the _Description_ field between the NC web client and the app. 

For example, the web client ignores things like # and <br>, but can display bullet points via *. In this app, the extra spacing is realized, but # and * are not.

**Comment by dmbreakey** [comment]
Clearly the web UI isn't using true Markdown, but it appears a subset of it. I may have to examine the code to try and understand what it's actually doing.

# is ignored because it uses that as a flag to link to other recipes. You type '#' and it immediately opens a pop-up allowing you to search for and select a recipe, allowing for inter-recipe links. Looks like you can also link into Tags and Categories, but I haven't quantified that yet.

Unfortunately that also doesn't work, as it embeds the wrong reference (it embeds #r/<recipe-id>, when it looks like it should be embedding #/recipe/<recipe-id>; I've had to manually fix that countless times over the last week, but I just haven't gotten around to filing a bug report for it yet; too many other things clamoring for attention).

**Comment by Teifun2** [comment]
Ive added General support for Markdown with
https://pub.dev/packages/flutter_markdown

I am unsure about the exact details of this markdown implementation but hope it is enough for now!

**Comment by Teifun2** [comment]
This is implemented with version 0.7.6
