### ISSUE TITLE
Build problems under Linux

### ISSUE THREAD

**Issue by prometheus42** [Teifun2/nextcloud-cookbook-flutter#89]
When opening some recipes in my collection with the app I get an error. To fix the problem I tried building the app myself. But after installing all necessary software some error messages prevent the build process from running successfully:

    Running Gradle task 'assembleDebug'...
    /home/christian/snap/flutter/common/flutter/.pub-cache/git/flutter_translate- 
    614d930a7d68b3b0b98492dce113fdfe3e2ad8f1/lib/src/services/localization.dart:29:16: Warning: Operand of null-aware 
    operation '??' has type 'String' which excludes null.
            return translation ?? key;
                   ^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_reorderable_list-1.1.0/lib/flutter_reorderable_list.dart:740:14: Error: Too few positional arguments: 3 required, 2 given.
          : super(initialPosition, kind) {
                 ^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:32:11: Error: No named parameter with the name 'delta'.
              delta: delta,
              ^^^^^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/scale.dart:339:43: Error: Too few positional arguments: 2 required, 1 given.
              focalPointDelta > computePanSlop(pointerDeviceKind))
                                              ^
    /home/christian/snap/flutter/common/flutter/packages/flutter/lib/src/gestures/events.dart:2116:8: Context: Found this candidate, but the arguments don't match.
    double computePanSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
           ^^^^^^^^^^^^^^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:46:66: Error: Too few positional arguments: 2 required, 1 given.
        final double minDistance = minFlingDistance ?? computeHitSlop(kind);
                                                                     ^
    /home/christian/snap/flutter/common/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
    double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
           ^^^^^^^^^^^^^^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:54:55: Error: Too few positional arguments: 2 required, 1 given.
        return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
                                                          ^
    /home/christian/snap/flutter/common/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
    double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
           ^^^^^^^^^^^^^^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:101:66: Error: Too few positional arguments: 2 required, 1 given.
        final double minDistance = minFlingDistance ?? computeHitSlop(kind);
                                                                     ^
    /home/christian/snap/flutter/common/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
    double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
           ^^^^^^^^^^^^^^
    /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-5.1.3/lib/src/gesture_detector/drag.dart:109:55: Error: Too few positional arguments: 2 required, 1 given.
        return _globalDistanceMoved.abs() > computeHitSlop(pointerDeviceKind);
                                                          ^
    /home/christian/snap/flutter/common/flutter/packages/flutter/lib/src/gestures/events.dart:2103:8: Context: Found this candidate, but the arguments don't match.
    double computeHitSlop(PointerDeviceKind kind, DeviceGestureSettings? settings) {
           ^^^^^^^^^^^^^^

I am using Android Studio Android Studio Arctic Fox (2020.3.1 Patch 3) under Ubuntu Linux (5.13.0-20-generic) with Flutter 2.7 on the Beta channel:

    Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel beta, 2.7.0-3.1.pre, on Ubuntu 21.10 5.13.0-20-generic, locale de_DE.UTF-8)
    [✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    [✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
        ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
    [✓] Linux toolchain - develop for Linux desktop
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.61.2)
    [✓] Connected device (2 available)

Because all error occur in library code, I assume the problem has something to do with different version of the build environment. I tried already to re-download all libraries and building outside of Android Studio on the command line.

Has someone an idea, what's causing the problem and how to fix it? Thanks in advance!

**Comment by Teifun2** [comment]
Can you test it with my pubspec.lock file? (to make sure we have all the same library versions!)

https://gist.github.com/Teifun2/50ab70354c9550b8b961bbb0600c3c54
Just copy my pubspec.lock file and den run `flutter pub get`

**Comment by prometheus42** [comment]
The build still fails using your pubspec.lock.

Also, I just tested switching flutter to channel master. But that did not help either, the error messages are still the same.

**Comment by prometheus42** [comment]
I just changed flutter to the stable channel and the build no works with only two warnings:

    /home/christian/snap/flutter/common/flutter/.pub-cache/git/flutter_translate-614d930a7d68b3b0b98492dce113fdfe3e2ad8f1/lib/src/services/localization.dart:29:16: Warning: Operand of null-aware operation '??' has type 'String' which excludes null.
            return translation ?? key;
                   ^
    Note: /home/christian/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_secure_storage-4.2.1/android/src/main/java/com/it_nomads/fluttersecurestorage/FlutterSecureStoragePlugin.java uses or overrides a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.

Seems that the switch to beta channel resulted in the error messages. Sorry for the confusion?! ;-)

**Comment by Teifun2** [comment]
Yes i have the same warnings. There is some "issues" in the library that i use for the translations but that should not be a problem.

No worries about the confusion that happens.

If you find anything that needs fixing please let me know :)
