### ISSUE TITLE
Error parsing recipe if instructions contain empty strings

### ISSUE THREAD

**Issue by prometheus42** [Teifun2/nextcloud-cookbook-flutter#90]
Most of my recipes have been converted from the XML file format of the Gourmet Recipe Manager to JSON format. When converting the recipes some empty paragraphs were saved as empty strings in the JSON list element `recipeInstructions` (see [JSON schema](https://schema.org/Recipe)). I uploaded a problematic recipe file here: [https://gist.github.com/prometheus42/fff4040bb75a40bc16a881d442351481](https://gist.github.com/prometheus42/fff4040bb75a40bc16a881d442351481)

When opening this recipe the app shows the following error:

    Exception: NoSuchMethodError: Class '_InternalLinkedHashMap<String, dynamic>' has no instance method 'cast' with matching arguments.
        Receiver: _LinkedHashMap len:2
        Tried calling: cast<String>()
        Found: cast<Y0, Y1>() => Map<Y0, Y1>

Checking the source the problem is located at the factory method for instantiating a new Recipe object (lib/src/models/recipe.dart:64). The runtime type of variable `recipeInstructions` is `_InternalLinkedHashMap<String, dynamic>` instead of `List<dynamic>` like `recipeIngredient`, for example. So the cast to a list of strings fails. I can not reconstruct why this one variable gets another type?!

As a solution the app could differentiate between the two runtime types by changing the line:

    recipeInstructions = data["recipeInstructions"].cast<String>().toList();

to the following code:

    List<String> recipeInstructions = [];
    if (data["recipeInstructions"] is Map) {
      data["recipeInstructions"].forEach((k,v) => recipeInstructions.add(v as String));
    } else {
      recipeInstructions = data["recipeInstructions"].cast<String>().toList();
    }

For my recipes this solution works! Don't know, if this is a good solution, so I did not prepare a pull request?! But I could do it, if that would help...

**Comment by Teifun2** [comment]
@prometheus42 
Hello i'm very sorry for my late response!

This is perfect analysis there! I checked your fix and it works perfectly!
I will use it for all three Ingredients / instructions and tools.

Next time feel free to directly open a pull requests!

Thanks for your contribution!

**Comment by wichmann** [comment]
@Teifun2
Thanks!
