### ISSUE TITLE
[Feature Request] Adjustable portions

### ISSUE THREAD

**Issue by coxtor** [Teifun2/nextcloud-cookbook-flutter#93]
Hi  - awesome app I really love it! 
It would be a great addition to be able to adjust the portions to be able to calculate the needed ingredients dynamically. 
Thanks!

**Comment by Teifun2** [comment]
Hi @coxtor 
Sadly i'm not able to provide this functionality on the side of the app alone as long as the nextcloud plugin itself does not support this.

This is a rather complicatd topic and i would reccomend you to read:
https://github.com/nextcloud/cookbook/issues/116

I will close the issue and pick up this topic if at some point the nextcloud plugin will support this.
